### ISSUE TITLE
Rename `mut_world` to `world_mut`

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#100]
Could you deprecate the old one (`Planner::mut_world`)? I think the getter convention in Rust is `my_variable_mut`.

**Comment by kvark** [comment]
This is not trivial. Our method is not *just* a getter, for which `my_variable_mut` is applicable. Our "mutate world" basically waits for everything to finish before returning to you, which is a heavier operation.

**Comment by torkleyy** [comment]
Agreed
