### ISSUE TITLE
Consider using futures

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#101]
Could you try [futures](https://github.com/alexcrichton/futures-rs) instead of `threadpool`? Probably make it an optional dependency? I think it would also be interesting in terms of performance.

Additionally, `amethyst` could reuse the `CpuPool` then (Probably make it an `Arc`?).

**Comment by torkleyy** [comment]
If you give me some hints / explanation / links how this parallel model works with `Pulse` and the channel, I'd try it myself.

**Comment by cjhowe** [comment]
Is this a duplicate of #42?

**Comment by torkleyy** [comment]
@cjhowe Oh you are right, it is covered by that, but anyways, I tried to implement that, but I don't think there is really an advantage (it would have been just an internal thing, anyways).
