### ISSUE TITLE
B-tree component storages

### ISSUE THREAD

**Issue by kvark** [slide-rs/specs#118]
Reading about them now: https://en.wikipedia.org/wiki/B-tree

They appear to be perfectly suited as component storages:
  - keep data in chunks, so there is not many data cache misses
  - sorted by keys, meaning that walking the entities will walk the values continuously
  - present in std: https://doc.rust-lang.org/stable/std/collections/struct.BTreeMap.html

**Comment by vitvakatu** [comment]
I want try to implement it. If it's not high priority :smile:
