### ISSUE TITLE
BTreeMap for all the storage

### ISSUE THREAD

**Issue by kvark** [slide-rs/specs#122]
It appears that `BTreeMap` is both efficient at removing/inserting elements as it is at iteration, giving mostly linear access and combining the benefits of vectors and maps. It seems like an ideal storage for components (see #119), thus I wonder... If we can go extreme and force all the storages to be `BTreeMap`. This would simplify some of the internals and some of the user code.

I haven't seen a good example of a user-defined storage type yet, so that might be the biggest question. If it's not useful, we can cut this ability.

**Comment by vitvakatu** [comment]
IMO, user-defined storage is usefulness in case we will provide efficient storage out-of-the-box.
If you're sure about it, I can prepare a PR in a few days.

**Comment by OvermindDL1** [comment]
User defined storage for me was usually for highly optimized iteration, like for performing SSE or OpenCL over, over which a map would not suffice.

**Comment by kvark** [comment]
Interesting, looks like the hashmaps work better for Postgres people: http://amitkapila16.blogspot.ca/2017/03/hash-indexes-are-faster-than-btree.html

**Comment by kvark** [comment]
Considering this to be fixed by #119
