### ISSUE TITLE
Make ticket feature additive

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#123]

**Comment by torkleyy** [comment]
@kvark Do you think just providing a `World` and a `GatedWorld` would be sufficient?

**Comment by kvark** [comment]
@torkleyy that's an interesting approach, definitely worth exploring. I hope to minimize code duplication.

**Comment by torkleyy** [comment]
@kvark OK, I'll try that

**Comment by torkleyy** [comment]
@kvark I've tried to do this in a clean way, but it wasn't possible without code duplication. But do we really need a non-ticket mode?

**Comment by kvark** [comment]
@torkleyy yes, I'd prefer the old path to remain. How much code roughly is going to be duplicated?

**Comment by torkleyy** [comment]
@kvark it's about 150 lines (the common part of both `World`s). I could solve that, by using a `BaseWorld` together with `Deref`, but I'm unsure how easy this is to grasp plus I don't think `Deref` is intended to be used for emulating inheritance. Additionally, there is no completion support for `Deref`. The other option would be to still have the base world and a lot of boilerplate methods.

**Comment by torkleyy** [comment]
@kvark should the `World` (= without tickets) be built always or should there be a `ticket` and a `noticket` feature?

**Comment by kvark** [comment]
@torkleyy it doesn't appear that we have a clean path to the additive `ticket` feature at this point. Splitting everything in pieces and implementing traits on them seems like an overkill. Let's keep looking. If we don't find a nice solution, we'll just remove the non-ticked code path.

**Comment by torkleyy** [comment]
@kvark yes, I agree. How likely is it my Pre-RFC is well-received?

**Comment by kvark** [comment]
@torkleyy I honestly don't know. Someone closer to crates.io may answer.
@carols10cents?
(question was: pre-RFC about non-compatible cargo features)

**Comment by carols10cents** [comment]
I'm not sure, I don't know the details around `feature`s very well :-/ maybe start with an issue on https://github.com/rust-lang/cargo?

**Comment by torkleyy** [comment]
Already opened topic [on internals](https://internals.rust-lang.org/t/pre-rfc-provide-flavors-for-libraries-non-additive-features/5079), however the Reddit link has 1 upvote... So I wouldn't expect it to get merged.

**Comment by torkleyy** [comment]
There is no good solution, removed feature via #127
