### ISSUE TITLE
Use rayon for parallel execution

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#124]
Would be great if Rust libraries would use one common threadpool and because [`rayon`](https://github.com/nikomatsakis/rayon) supports [parallel iterators, futures, scoped and static parallelism as of 0.7](http://smallcultfollowing.com/babysteps/blog/2017/04/06/rayon-0-7-released/), it is the ideal choice!

If there are no concerns, I'll implement it.

**Comment by WaDelma** [comment]
I actually started implementing this in #120, but got stuck plumbing it through specs. It also was before 0.7 and relied on unstable internal API which now is stable.

I should really look again into it, but if you want to you can do it too either using what I did as basis or discarding it if it's bad (I am not that confident on how good it's approach is).

**Comment by torkleyy** [comment]
@WaDelma I've already implemented it, but only as a thread pool. So it doesn't yet address https://github.com/slide-rs/specs/issues/54, which can still be done later.
