### ISSUE TITLE
Optimize VecStorage

### ISSUE THREAD

**Issue by kvark** [slide-rs/specs#13]
It's currently implemented as `Vec<Option<T>>`, thus blowing up the size by a machine word, with only one bit really used. This reduces cache efficiency. Instead, we can have a separate bit vector.

**Comment by kvark** [comment]
Note: this will either require unsafe (for `mem::uninitialized`), or `T: Default`, none of which are desirable.

**Comment by csherratt** [comment]
I actually have tried this here is the performance graphs

![gets_inorder](https://cloud.githubusercontent.com/assets/62622/14405782/a925da3a-fe63-11e5-87a1-19e1f0b7dfd7.png)

![gets_rand](https://cloud.githubusercontent.com/assets/62622/14405784/abe04aa8-fe63-11e5-9d8d-d3f4b7652d41.png)

**Comment by kvark** [comment]
Wow, very nice! Do you have an explanation though?

Also, this leaves me wondering about what else can be optimized there... Perhaps, when 'NonZero' is stable, we'd automatically get the boost for user components that implement it, due to Option coming for free.

**Comment by csherratt** [comment]
Sorry should have given more explanation.

`VecMap` is the vecmap from crates.io vecmap. Not the one you wrote. They should perform almost identically. `VecMapNew` is the bitmask version. I used a u64 in a separate vector from the data.

Basically, `Option<T>` is going to be faster in most cases, it's marginal but measurable. Random access ends up being faster for bitmask solution once the table is bigger then the L2 cache. But this access pattern should be avoided if possible.

**Comment by kvark** [comment]
@csherratt I understand what you were doing. The explanation I asked for was why the new version is slower, considering the fact it needs to read less data.
