### ISSUE TITLE
Profile ecs_bench

### ISSUE THREAD

**Issue by kvark** [slide-rs/specs#132]

**Comment by torkleyy** [comment]
Current status: As far as dispatching goes, Specs is leading the benchmarks / has in some cases comparable results with `calx-ecs` and `froggy` (in the parallel build). Given that Travis isn't good at multi-threading, I don't think we should worry about those benchmarks.

This issue has been created after other libraries lead the benchmarks, is there anything left to do here?

**Comment by kvark** [comment]
Time to close it :+1:
