### ISSUE TITLE
[Question] Access underlying storage data

### ISSUE THREAD

**Issue by wspowell** [slide-rs/specs#140]
I am experimenting with specs. What I want to do is access the `Vec<T>` inside `VecStorage<T>` so that I can apply a `vec.sort_by()` (or any `Vec<T>` function, really). So far, I have not found a way to do this. Also, I would like to keep using a `Vec<T>` and not have to use a `BTreeMap<T>` for various reasons. 

What I am trying to do would look something like:
```rust
let (mut foo, .. ) = arg.fetch(|w| {
    (w.write::<CompVec>(), .. )
});

// Do something interesting with foo.

// Sort the underlying component data.
foo.storage().sort_by( .. );
```

**Comment by kvark** [comment]
Why would you want to sort the components?

**Comment by wspowell** [comment]
I am experimenting with Amethyst which uses specs. When iterating over each entity, I want to be able to know that the one before/after it is less/greater. Also, I want to be able to control when the sorting occurs and keep the data stored in a contiguous data structure. I was hoping that since (in my particular case) updates to each entity's component data occurs frequently, but the actual ordering does not change, that I could save the reinsertion cost of the BTreeMap and have relatively fast Vec sorting (since according to the docs, it is designed to be fast in cases where it is nearly sorted).

I am not doing this with all of my components. Just in the one use case.

**Comment by kvark** [comment]
Are you going to iterate the contents of the component directly, or are you going to iterate the entities and access this component? In the latter case (and that appears to be the case for you, if I read correctly), it doesn't matter if the component data is ordered, since the order of entities is used anyway.

Thus, in order to "be able to know that the one before/after it is less/greater", you'd actually need to re-order entities. Doing it mutably in `specs` could be possible, but essentially would require all the component storages to be affected. Alternatively, you could store a `Vec<Entity>` somewhere and use it for iteration.

**Comment by wspowell** [comment]
Could you help me understand which case this is using?
```rust
let (mut foo, entities) = arg.fetch(|w| {
    (w.write::<CompVec>(), w.entities())
});

// Which case is this?
// 1) Iterating over the contents of the components directly, or
// 2) Iterating over the entities and accessing the component
for (bar, eid) in (&mut foo, &entities).join() {
    // Do something interesting.
    // Is the order of the entities being used here?
}
```
Follow up question, how would you go about iterating over the contents of the components directly? If I can do this, could I also sort the component data somehow?

If not, then I might just fall back to what you suggested and store a `Vec<T>` as a resource in the `World`.

**Comment by kvark** [comment]
Your case iterates the component data in the entities order. In fact, for a `Vec` storage these are equal - entities correspond to indices in the vector, so both orders are the same.

Let's say you implemented your own storage type `MyStorage` and used it on a component. You got `w.write::<Component>()` in the fetch, assigned it to `storage_lock` variable, and then trying to iterate it directly (unattached to entities). You'd do `storage_lock.open_mut().1` (see [open_mut](https://github.com/slide-rs/specs/blob/16851e39a09e0f66e8142d6f171c1028bb21f38e/src/storage.rs#L37)) to get the actual inner storage mutably, then use methods of `MyStorage` or its exposed public fields to iterate/change it.

Our current storage types don't publicly expose the contents, but we may revise it if there is a strong use case.

**Comment by wspowell** [comment]
Thanks for your help!

**Comment by torkleyy** [comment]
@wspowell You may also want to check out [this repo's Gitter channel](https://gitter.im/slide-rs/specs) for future questions.
