### ISSUE TITLE
Unique entity Id

### ISSUE THREAD

**Issue by n0uk** [slide-rs/specs#148]
Hi!

It would be great, to have something like 

```
impl Entity {
...
    /// Returns the unique id of the `Entity`.
    #[inline]
    pub fn get_uid(&self) -> i64 {
        (self.1).0 as i64 | ((self.0 as i64) << 32)
    }
...
```

Or:

```
impl Entity {
...
    /// Returns the generation of the `Entity`.
    #[inline]
    pub fn get_gen_id(&self) -> i32 {
        (self.1).0
    }
...
```

Because now, generation id field is private, and create component for storing unique id of every entity looks like overhead.

**Comment by kvark** [comment]
Isn't it unidiomatic to ECS in general? My understanding was that an entity is fully described by a set of components, there is no identity to it otherwise.

**Comment by kvark** [comment]
If it's useful to you, I don't mind us exposing this method.

**Comment by pedrohjordao** [comment]
Access to Id would be useful if you need to uniquely identify and update a entity over a network (the entity is a created on the server, sent to a client, the client updates it and send it back to the server to propagate the update to other clients)

**Comment by pedrohjordao** [comment]
This is my first time using an ECS and server/client architecture at the same time, if there is an alternative to update using the entity id I'd be interested in knowing about it.

**Comment by kvark** [comment]
@Aceeri - given that you did a lot of work on serialization, would you mind sharing your opinion about this PR?

**Comment by OvermindDL1** [comment]
> Isn't it unidiomatic to ECS in general? My understanding was that an entity is fully described by a set of components, there is no identity to it otherwise.

Not necessarily.  An Entity can exist without components.  I've always used a 64-bit integer (part of it a generation, part an index) as an entity ID in my systems, I just access things like `SomeComponentTable.get(entityID)` or so.  I often use the ID in various things.

**Comment by n0uk** [comment]
Yes, as says @pedrohjordao it's very useful for networking in my case. I'm new to ECS, so not sure is it idiomatic or not, but in this post for example:

http://t-machine.org/index.php/2007/12/22/entity-systems-are-the-future-of-mmog-development-part-3/

Adam Martin talk about entity as GUID.

**Comment by vitvakatu** [comment]
I can not see any reason it can be bad for `specs`, so why not?

**Comment by Aceeri** [comment]
Well, I've been thinking of networking with specs for a bit now and I'm thinking there may be a need for either a unique id unrelated to the index or a way for a server to be completely authoritative in which entities are created on the client.

However, I don't see a reason why the generation couldn't be public.

**Comment by kvark** [comment]
Great, thanks for all the feedback! Sounds like a consensus.

**Comment by torkleyy** [comment]
Related to #138
