### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#157]
TL;DR the Rust ecosystem is largely Apache-2.0. Being available under that
license is good for interoperation. The MIT license as an add-on can be nice
for GPLv2 projects to use your code.

## Why?

The MIT license requires reproducing countless copies of the same copyright
header with different names in the copyright field, for every MIT library in
use. The Apache license does not have this drawback. However, this is not the
primary motivation for me creating these issues. The Apache license also has
protections from patent trolls and an explicit contribution licensing clause.
However, the Apache license is incompatible with GPLv2. This is why Rust is
dual-licensed as MIT/Apache (the "primary" license being Apache, MIT only for
GPLv2 compat), and doing so would be wise for this project. This also makes
this crate suitable for inclusion and unrestricted sharing in the Rust
standard distribution and other projects using dual MIT/Apache, such as my
personal ulterior motive, the Robigalia project.

Some ask, "Does this really apply to binary redistributions? Does MIT really
require reproducing the whole thing?" I'm not a lawyer, and I can't give legal
advice, but some Google Android apps include open source attributions using
this interpretation. Others also agree with
it.
But, again, the copyright notice redistribution is not the primary motivation
for the dual-licensing. It's stronger protections to licensees and better
interoperation with the wider Rust ecosystem.

## Contributor checkoff

To agree to relicensing, comment with :

> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

## Checklist

- [x] @kvark 
- [x] me
- [x] @Aceeri 
- [x] @serprex 
- [x] @vitvakatu 
- [x] @malleusinferni 
- [x] @thiolliere 
- [x] @murarth 
- [x] @jeffparsons 
- [x] @msiglreith 
- [x] @lschmierer 
- [x] @WaDelma 
- [x] @Kimundi 
- [x] @mrZalli 
- [x] @Jragonmiris 
- [x] @minecrawler 
- [x] @futile 
- [ ] @White-Oak

**Comment by jeffparsons** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

**Comment by murarth** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by msiglreith** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by malleusinferni** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by serprex** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Aceeri** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by vitvakatu** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by thiolliere** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by lschmierer** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by WaDelma** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Kimundi** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by mrZalli** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by torkleyy** [comment]
Ping

@futile 
@White-Oak 
@minecrawler

**Comment by minecrawler** [comment]
Sorry for the delay!

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by futile** [comment]
Sorry for the delay!

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by willglynn** [comment]
I wasn't on the list, but I am now a contributor, so:

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by torkleyy** [comment]
Thank you, but the readme already states that contributions have this license, so new contributions are not affected.

**Comment by torkleyy** [comment]
@White-Oak still didn't respond :(

**Comment by Aceeri** [comment]
@torkleyy Other projects I've seen get stuck on a couple inactive contributors usually just go the route of changing the license and telling the remaining people if they have an issue with the new license we'll look at rewriting the contributions.

**Comment by mrZalli** [comment]
@Aceeri Seems like they've been inactive since May. That sounds like the best solution.

**Comment by torkleyy** [comment]
OK, this issue is ready now.

## Steps

* Add the MIT license
* Rename apache license to `LICENSE_APACHE`
