### ISSUE TITLE
Component Wrappers

### ISSUE THREAD

**Issue by Aceeri** [slide-rs/specs#168]
Storages like `FlaggedStorage` and `ChangedStorage` (I'm assuming most "wrapper" storages as well) could be improved if it was possible to return wrapper types instead of just components themselves:
```rust
pub trait UnprotectedStorage<T> {
    type Wrapper<'a>;
    type WrapperMut<'a>;
    ...
    fn get<'a>(&'a self) -> Self::Wrapper<'a>;
    fn get_mut<'a>(&'a mut self) -> Self::WrapperMut<'a>;
    ...
}

impl<T> UnprotectedStorage<T> for ChangedStorage {
    type Wrapper<'a> = &'a T;
    type WrapperMut<'a> = Tracked<&'a mut T>;
    ...
    fn get<'a>(&'a self) -> &'a T { ... }
    fn get_mut<'a>(&'a mut self) -> Tracked<&'a mut T> { ... }
    ...
}
```

Alternatively:
```rust
pub trait UnprotectedStorage<'a, T> {
    type Wrapper: 'a;
    type WrapperMut: 'a;
    ...
    fn get(&self) -> Self::Wrapper;
    fn get_mut(&mut self) -> Self::WrapperMut;
    ...
}

impl<'a, T> UnprotectedStorage<'a, T> for ChangedStorage {
    type Wrapper = &'a T;
    type WrapperMut = Tracked<'a, &'a mut T>;
    ...
    fn get<'a>(&'a self) -> &'a T { ... }
    fn get_mut<'a>(&'a mut self) -> Tracked<'a, &'a mut T> { ... }
    ...
}
```

Since it would eliminate the need for things like `maintain` methods and ease overall usage of the storages to be used similar to any other.

Sadly, I don't think it is possible in current Rust's type system until either we get lifetime ATCs or a non-'static `TypeId` (since this is what prevents just adding a lifetime to the `UnprotectedStorage<T>`.

**Comment by omni-viral** [comment]
It is possible with little boilerplate.
```rust
trait Wrapper<'a> {
  type Mut;
  type Ref;
}

trait UnprotectedStorage<T> {
  type Wrapper: for<'a> Wrapper<'a>;
  fn get<'a>(&'a self) -> <Self::Wrapper as Wrapper<'a>>::Ref;
  fn get_mut<'a>(&'a mut self) -> <Self::Wrapper as Wrapper<'a>>::Mut;
}
``|

**Comment by torkleyy** [comment]
I think this would unnecessarily complicate the API. If you need such a special solution you can just as well create your own component storages (which is quite easy as can be seen in `specs-static`).
