### ISSUE TITLE
Allocator / Generations

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#178]
I think the current implementation has several limitations, which are unpractical:

* A component may contain an entity which has been deleted
    * accessing anything with that entity makes the application crash
    * deleting an entity involves deleting all components referencing it; this requires one system to know about data which is totally unrelated
    * going from the above point, extensibility is limited because you cannot simply add another component (with references to another entity) without all the systems knowing about it
* Entity always have to be proven A) alive and B) being of the latest generation
    * Performance
    * Easy to get wrong so missing check in our implementation could cause UB in some cases
* Constantly creating and deleting entities might lead to an integer overflow in the `Generation`

---

First of all, this is a rather complex topic, so there's no easy solution. I have thought of some points concerning what should be allowed, which checks we should do and what kind of ergonomics we want to provide; I'd like to present these in the next sections.

## Assertion of validity

1) Having invalid entities is both unpractical and doesn't allow for robust applications

If one stores an entity in a component, it's not feasible to ask for checking if it's alive or dead.
However, not doing so makes the application crash at the moment.

Conclusion: Given an instance of `Entity`, it's validity should be guaranteed.

2) Retrieving the component of an "old" entity (which died and revived, but the copy did not) returns `None`

and may be rather hard to debug.

Conclusion: `None` should only be returned if there's no component associated with that entity; given that an instance is always valid, this should be very easy to implement then.

## Deletion of entities

The `maintain()` method should not only delete components of the deleted entities, but also the components which reference this entity. For that, a `Component` implementation may provide a method `references_entity(&self, e: &Entity) -> bool` which provides that information, so the storage can delete those components.

---

I'm not sure about other parts, but this issue needs much time to be solved anyways, so I hope we can collect some ideas here.

**Comment by jonas-schievink** [comment]
Is deleting components that reference the entity really the right approach? Forgive me if this sounds dumb, I don't have much experience with specs (yet), but if a component references entities, shouldn't it be forced to deal with entities that get deleted?

Maybe it would be useful to list the kinds of use cases where a component references entities. It looks to me like this is needed mainly in cases where entities interact in some way.

For example, I could have an `AiComponent` that makes the entity walk circles around a target entity (or some other arbitrarily complex behaviour). In this case, it must be able to deal with the fact that the target may be deleted (dies), presumably by searching for a new target or changing to an idle mode when there is none, having the component deleted without further notification is not ideal, since it would likely cause the entity that used to have this component to stop moving completely.

Just my 2 cents, what are your thoughts? Am I completely off track?

**Comment by torkleyy** [comment]
@jonas-schievink 

> Forgive me if this sounds dumb

It does not, I'm very happy about your input.

> In this case, it must be able to deal with the fact that the target may be deleted (dies), presumably by searching for a new target or changing to an idle mode when there is none, having the component deleted without further notification is not ideal, since it would likely cause the entity that used to have this component to stop moving completely.

You're right! Given that, do you have an idea how deal with it? Is just calling `entities.is_alive` okay / enough ergonomic? And should we worry about the generation overflowing?

**Comment by WaDelma** [comment]
Would it be possible to have something like `Weak` for entities? So that before you can use it you have to promote it to real entity which can fail if it's already deleted. Dunno just spitballing here.

**Comment by jonas-schievink** [comment]
> Is just calling entities.is_alive okay / enough ergonomic?

I *think* `is_alive` is basically what I would expect. Maybe we can treat `Entity` more similar to an `Option` (since it basically is one), but I'm not sure how that would look.

> And should we worry about the generation overflowing?

Really not sure about that. Maybe look into other ECS using such a generation system since they'd have to deal with this, too?

**Comment by torkleyy** [comment]
> Maybe look into other ECS using such a generation system

Well, try finding an ECS that is

1) parallel
2) with generation ids

These two criteria will decimate the results to a number near to 0.

**Comment by Aceeri** [comment]
> However, not doing so makes the application crash at the moment.

I don't think there is a way to get a component directly with an `Entity` anywhere? You only get an `Option<&C/&mutC>` unless you do some hackery and expose the `UnprotectedStorage` at which point you brought it upon yourself.

I doubt the generational id would overflow, but if we are really worried about that we can just up it to an `i64`.

**Comment by kvark** [comment]
> deleting an entity involves deleting all components referencing it; this requires one system to know about data which is totally unrelated

How is this true? A system doesn't manually delete all components, it just tells the world to delete an entity, and the world deletes the components. So there is no need for a system to know about components.

> The maintain() method should not only delete components of the deleted entities, but also the components which reference this entity.

I don't think these need to be deleted. At max - notified somehow. At min - left to do their own thing involving `is_alive` checks.

---

But really, its these kinds of questions that made me realize CGS, so the answer is [froggy](https://github.com/kvark/froggy). In froggy, storing "entity IDs" in components is natural, and component is guaranteed to be alive for as long as there is a pointer to it, so the access is truly zero cost. Perhaps, we could borrow some of the machinery involved there for Specs?..

**Comment by torkleyy** [comment]
> How is this true? A system doesn't manually delete all components, it just tells the world to delete an entity, and the world deletes the components.

I was talking about this:

```rust
struct Link {
    a: Entity,
    b: Entity,
}
```

So you're saying it's the job of some physics system to check if entities are alive for every link and for every spring?

**Comment by kvark** [comment]
> So you're saying it's the job of some physics system to check if entities are alive for every link and for every spring?

It's not a terrible solution, given that it's already possible, and we have no idea how that physics system would look like. I'd prefer seeing a use case live first, before bringing the radical architectural changes to address it.

**Comment by torkleyy** [comment]
Agreed with all the points. Thanks for taking part in the discussion! Closing.
