### ISSUE TITLE
CheckedStorage cannot be used with par_iter

### ISSUE THREAD

**Issue by WaDelma** [slide-rs/specs#190]
Because `<CheckedStorage as Join>::Value` is `*const Storage<'e, T, D>` it cannot be used with `par_iter` as it isn't `Send`.

There is same problem with `Entry`, but you can implement `Send` for it.

**Comment by WaDelma** [comment]
So is this resolved by #203 now?

**Comment by torkleyy** [comment]
We still need to test it, that's why this issue isn't closed yet.
