### ISSUE TITLE
specs expects 'unstable' feature of rayon-core

### ISSUE THREAD

**Issue by robojeb** [slide-rs/specs#193]
I have run into an issue compiling specs 0.9.0. 

No matter what branch I utilize (1.17.0, 1.18.0, 1.19.0-beta, 1.19.0-nightly) I get the following error
```
cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: Package `rayon-core v1.2.0` does not have these features: `unstable`
```

I can't seem to track down what is specifically trying to request the unstable feature.
Though I may be screwing something up.

**Comment by kvark** [comment]
Relevant commit - https://github.com/nikomatsakis/rayon/commit/20de1ff12df93c739152e5ccfe48a91a66adac99

Please force an earlier version of rayon-core in the meantime, while we are going to fix specs.
@torkleyy this is rather unfortunate that we relied on an unstable feature, we shouldn't have released it then.

**Comment by torkleyy** [comment]
@robojeb Sorry for breaking your build. @kvark You're right, we shouldn't have. I fixed it and will release in a few minutes, please upgrade to Specs 0.9 then.
