### ISSUE TITLE
Add judy array as storage type

### ISSUE THREAD

**Issue by WaDelma** [slide-rs/specs#204]
Add and benchmark [judy array](https://github.com/adevore/rudy/) as possibly faster storage.

@torkleyy I noticed you were interested in adding it as storage so I figured I would create issue for it so it doesn't get forgotten.

**Comment by willglynn** [comment]
I took a whack at this and hit a couple snags, first of which was that the current `rudy` crate's `RudyMap` has no `remove()`. After switching to a git checkout (and building with nightly), I got everything wired up behind a feature flag, and found five of the usual storage tests fail against `RudyMap`.

I pushed this to a [`rudy` branch](https://github.com/willglynn/specs/tree/rudy) but have no immediate plans to open a PR.

**Comment by adevore** [comment]
The bug in Rudy has been fixed in master. I ran the tests locally on the rudy branch of specs and all tests pass.

**Comment by willglynn** [comment]
@WaDelma @torkleyy Would you like me to open a PR now (as an optional dependency pointing to git), or would you prefer me to wait for a followup `rudy` release?

**Comment by WaDelma** [comment]
I would prefer if I didn't accidentaly introduce the bug you encountered :P

We cannot release new version of `specs` before the fixed version of `rudy` is released, so I would prefer waiting for it.

**Comment by torkleyy** [comment]
A PR would be nice, yeah :+1:

**Comment by willglynn** [comment]
`RudyStorage` landed in #222, so this issue can be closed.

**Comment by torkleyy** [comment]
Probably not, we still need proper benchmark results and a secrion in the book.

**Comment by willglynn** [comment]
Ah! You are correct. This is what I get for trying to cover all my tabs with time-limited Internet access :-) Cheers!
