### ISSUE TITLE
Lazy Insertion

### ISSUE THREAD

**Issue by Aceeri** [slide-rs/specs#213]
Constructing an entity while the world is running isn't very ergonomic right now and the naive way of doing it can lead to almost no parallel systems (Accessing each storage required for construction mutably, so it blocks all other systems using that storage). A better approach is something like an "initialization" system where it is possible to insert a flag component that signifies that a certain component should be inserted. For example:
```rust
struct Position { x: f32, y: f32, z: f32 };
struct InitPosition;
struct InitPositionSystem;
impl<'a> System<'a> for InitPositionSystem {
    type SystemData = (
        Entities<'a>, 
        WriteStorage<'a, Position>, 
        ReadStorage<'a, InitPosition>
    );
    fn run(&mut self, (entities, positions, inits): Self::SystemData) {
        for (entity, _) in (&*entities, &inits).join() {
            positions.insert(entity, Position { x: 0.0, y: 0.0, z: 0.0 });
        }
    }
}
```

I feel like this could be abstracted over a bit by allowing some sort of lazy insertion method for the world. So instead of having to set up all this for an initialization system, you could just do something like:
```rust
impl<'a> System<'a> for SomeSys {
    type SystemData = (
        LazyInsert<'a>,
        Entities<'a>, 
    );
    fn run(&mut self, (lazy, entities): Self::SystemData) {
        for entity in (&*entities).join() {
            if ... { // some condition to insertion or something
                lazy.insert::<Position>(entity, Position { x: 0.0, y: 0.0, z: 0.0 });
            }
        }
    }
}
```
This would put the component into some queue in the world, so then once the world is maintained it inserts the components.

**Comment by minecrawler** [comment]
Is adding an entity (as opposed to a component) also affected by this slowdown?

```rust
let mut world: World;

// ...

impl System for ... {
    fn run(&mut self, entities: Entities) {
        if ... { // some condition to insertion or something
            let new_entity = world.create_entity().build();
        }
    }
}
```

**Comment by Aceeri** [comment]
Well, you are unable to actually get the world in a system, so entities can only be created atomically with the `EntitiesRes` struct.
