### ISSUE TITLE
Guided Joins

### ISSUE THREAD

**Issue by Aceeri** [slide-rs/specs#219]
Right now joins only allow in order iteration with entities, which works for most use cases. In some use cases, however, you need a sorted way of doing things to make sure the order of operation is correct. (For example, `amethyst`s transform system/scene graph).

So I propose a `GuidedIter`:
```rust
pub struct GuidedIter<I, J> {
    guide: I,
    bitset: J::Mask,
    values: J::Value,
};

impl<I, J> Iterator for GuidedIter<I, J>
    where I: Iterator<Item = usize>,
          J: Join,
{
    type Item = J::Type;
    fn next(&mut self) -> Option<J::Type> {
        while let Some(index) = self.guide.next() { 
            if self.bitset.contains(index) {
                return Some(index);
            }
        }
        None
    }
}
```

Usage:
```rust
let list: Vec<usize> = vec![5, 1, 8, 2, 9, 12];
for (comp1, comp2) in (&comp1s, &comp2s).guided_join(list) {
    ...
}
```

**Comment by torkleyy** [comment]
@Aceeri How would you know the order of components in advance?

**Comment by Aceeri** [comment]
The order of the components should be the same as the join that is used for the guided if that is what you are asking.

**Comment by Object905** [comment]
[Relevant](https://gitlab.com/nathanfaucett/rs-specs_guided_join)

**Comment by torkleyy** [comment]
As noted by @Object905, if somebody wants this feature they can use `specs_guided_join`.
