### ISSUE TITLE
Does Vec satisfy the DistinctStorage guarantee?

### ISSUE THREAD

**Issue by willglynn** [slide-rs/specs#220]
`pub unsafe trait DistinctStorage` is described as:

> This is a marker trait which requires you to uphold the following guarantee:
> 
> > Multiple threads may call `get_mut()` with distinct indices without causing
> > undefined behavior.
> 
> This is for example valid for `Vec`:
> 
> ```rust
> vec![1, 2, 3];
> ```
> 
> We may modify both element 1 and 2 at the same time; indexing the vector mutably
> does not modify anything else than the respective elements.
> 
> As a counter example, we may have some kind of cached storage; it caches
> elements when they're retrieved, so pushes a new element to some cache-vector.
> This storage is not allowed to implement `DistinctStorage`.
> 
> Implementing this trait marks the storage safe for concurrent mutation (of distinct
> elements), thus allows `join_par()`.

As I read this, I thought about how `Vec`s densely pack values, including things like [3-byte structs](https://is.gd/uYHT3y), which means `Vec` elements can be unaligned and/or smaller than the processor's native memory addressability. A write to a single 3-byte element would be executed as a 4- or 8-byte read/modify/write on ARM, and it would be legal to optimize into that on x86.

Then I thought about `&mut`s don't require atomic loads or stores, so the compiler is free to rearrange or optimize away memory operations without thinking about concurrency at all. This freedom extends to the CPU too -- different processors modifying distinct elements in the same cache line are free to perform independent read/modify/write cycles using independent caches, which means writes from one processor will not necessarily be seen before getting overwritten by other processors.

Is it safe to concurrently mutate adjacent `Vec` elements without memory barriers? What makes it so? Is this universally true for all `Vec`s on all architectures?

**Comment by WaDelma** [comment]
I am not sure about this, but I was able to do [this](http://play.integer32.com/?gist=6d8316c7ed7cd4ecfcd67471e676f701&version=stable) in perfectly safe rust.

**Comment by torkleyy** [comment]
cc @nikomatsakis

**Comment by jonas-schievink** [comment]
> A write to a single 3-byte element would be executed as a 4- or 8-byte read/modify/write on ARM, and it would be legal to optimize into that on x86.

This doesn't seem right. Size and stride of the struct is 3 bytes, there is no guarantee that the following byte is even readable or writable as it might be in another page. Can anyone demonstrate the use of 4-byte r/w instructions here?

**Comment by willglynn** [comment]
On a good night's rest, I think I have some answers:

* It's _not_ legal to compile byte stores to larger-than-byte load/modify/stores.
* Addressability concerns come from unaligned larger-than-byte loads/stores, not byte loads/stores. Platforms that have addressability concerns can paper over them over by emulating e.g. an unaligned `u16` store as a pair of `u8` stores. This costs of performance, but not correctness; storing a `u16` results in overwriting only the bytes in question with no R/M/W cycles on adjacent bytes.
* Cache coherence protocols ensure that a store -- even a regular, non-atomic store -- to part of a cache line invalidates everyone else's copy of that cache line. If multiple threads want to write multiple bytes to the same cache line, these writes will get serialized, again at costing performance but preserving correctness.

Put together, this means that everything in the memory subsystem can happen in any order, without barriers, and it all Just Works™. As long as the different threads load/store completely disjoint sets of bytes, there's no data races and no UB.

**Comment by torkleyy** [comment]
That's great to here! I'm very glad it turned out to be correct. But still thanks for sharing your concerns @willglynn!

**Comment by nikomatsakis** [comment]
see also https://github.com/nikomatsakis/rust-memory-model/issues/43, which seems relevant
