### ISSUE TITLE
How should my game loop look using specs?

### ISSUE THREAD

**Issue by bjadamson** [slide-rs/specs#224]
Hi, I have a question. It's unclear to me going through the examples/documentation how I should integrate specs into a program that runs infinitely. From what I see, all the examples/tests run once and then exit.

I'm trying to figure out how I should integrate specs into my game I've already been working on. Before specs I use an infinite loop to drive my game. I thought the dispatcher's dispatch() method looped infinitely, but (thankfully) it seems like it doesn't. When I invoke the [dispatcher's dispatch() method](https://github.com/bjadamson/softland/blob/874cfd3c444d9d9c2a63cdbaa54b1c20e51734ae/src/main.rs#L188) it seems to invoke each system once in parallel. Is my understanding here correct?

If that is correct, would the normal usage for a game to be something like this?

```
fn main() {
    /// initial game setup stuff ...
    ...

    ///  later on the game's infinite loop
    let mut dispatcher = DispatcherBuilder::new()
        .add(...)
        .build();
    loop {
        dispatcher.dispatch();
    }
}
```

If so, how would I ever quit this game loop? I seem unable to yield any reference to any bool that could checked in this loop to any of the systems, unless I use something like an Arc<T>?

Would that be the canonical way of communicating between a system and a boolean to control this game loop?

As you can see, I've got some confusion! I appreciate any help you can offer, hopefully my lack of understanding can be illuminating to you.

edit: typo

**Comment by WaDelma** [comment]
We are currently handling events in main thread and just checking if player presses escape or there is closing event and just setting boolean. We also transform relevant events to actions and send the actions via channel to be processed by players movement logic.

If you want to have a system setting the boolean, I would use [resource](https://slide-rs.github.io/specs-website/docs/book/0.9/04_resources.html). If there is multiple places that could potentially stop the game, I would have `AtomicBool` inside the resource so that you can process multiple systems that can set it same time.

**Comment by torkleyy** [comment]
To eloborate a bit, you have two options:

Do the event handling in systems or just in the loop. Now, if you're going for the former approache, you'd want to do something like this:

```rust
loop {
    dispatcher.dispatch(&mut world);

    if !*world.read_resource::<Running>() {
        break;
    }
}
```

Your events can just be stored in a resource and polled the way you like it.

**Comment by bjadamson** [comment]
Thanks, this helped a lot. I was able to organize my code so that it makes sense again (after a git reset --hard hehe).

I appreciate the help! To anyone in the future, if you want you can study my change [here](https://github.com/bjadamson/softland/commit/b03a760ef270954dd5ec81dcd60361a085ccff7a).
