### ISSUE TITLE
Undocumented constraint: custom systems must call `arg.fetch`.

### ISSUE THREAD

**Issue by jakerr** [slide-rs/specs#23]
In practice a system probably will always call `arg.fetch` before doing any other work but it probably shouldn't be required. The code currently enforces it waiting on the `signal` associated with the `pulse` in FetchArgs ensuring that it was not dropped.

If fetch is never called the signal is dropped and the task panics with a bit of a confusing message:

``` rust
if signal.wait().is_err() {
    panic!("task panicked before args were captured.")
}
```

[lib.rs#L120](https://github.com/kvark/parsec/blob/50dd598/src/lib.rs#L120)

If the current behavior is desired it should be documented and maybe the panic should hint something to the effect of: "Maybe you forgot to call arg.fetch from within your system closure".

**Comment by kvark** [comment]
Thank you, that is reasonable. I wish we could enforce this at compile time.

**Comment by malleusinferni** [comment]
> I wish we could enforce this at compile time.

It seems to me like you could abuse the type system to make this work. Instead of having `arg.fetch()`, add an associated type to the `System` trait that describes what's being fetched. For example:

```rust
impl System<Ctx> for Motion {
    type Captures = (RW<Position>, RO<Velocity>);

    fn run(&mut self, args: Captures, env: RunArg, ctx: Ctx) {
        // Iterate over args
        // RunArg is still around for entity/component creation/deletion
    }
}
```

The obvious drawback is that you can no longer write systems that choose their captures at runtime, but judging by #51, that's an acceptable tradeoff.

**Comment by kvark** [comment]
@malleusinferni the approach with associated types is impossible by 2 reasons:
  1. the `Captures` type would have to depend on the lifetime, and we don't have higher kind lifetimes support in the language.
  2. we wouldn't be able to box systems like we do now:
```rust
    /// System trait object itself.
    pub object: Box<System<C>>,
```

**Comment by malleusinferni** [comment]
Shucks.

**Comment by jFransham** [comment]
Hi, so I actually ran into this exact problem before (`Captures` depending on the lifetime) and I fixed it with ridiculous type system hackery, the ultimate upshot of which is that you specify `&'static` in the associated type and then the function receives a type with a more constrained lifetime. Check out the implementation [here](https://github.com/jFransham/ecs-rs) - specifically, on [this line](https://github.com/jFransham/ecs-rs/blob/master/src/components.rs#L35). That ECS isn't production-ready or anything, but it was a really fun project and it might be useful to check out with relation to this.

**Comment by WaDelma** [comment]
Does fetch need to borrow `self`? If it was made to take ownership it would ensure that it cannot be called more than once.

And to ensure that it is called atleast once it could have destructor that panics and have the fetch forget `self`.

**Comment by WaDelma** [comment]
Ah yeah it has more than fetch methods...
Maybe the RunArg could have `Cell<bool>` indicating if fetch has been used and have fetch panic if it's already set and destructor panic if it's not set.

**Comment by kvark** [comment]
@WaDelma yes, some sort of run-time panic would be an improvement. I think it already has a flag in a shape of `RefCell<Option<Pulse>>`.

**Comment by WaDelma** [comment]
I'll try to add it?

**Comment by WaDelma** [comment]
I tried to use `drop` to give better error message, but it causes double panic with the 'task panicked before args were captured.' thing. Could that error message be just improved? I also tried to add test for both cases (one for calling fetch zero times and one for calling fetch two times), but the two times one doesn't work with  `should_panic` because of threads (this was the problem with `_task_panics` test, right?)
