### ISSUE TITLE
Format book examples

### ISSUE THREAD

**Issue by WaDelma** [slide-rs/specs#252]
Examples in book are still using old formating (examples in API documention may have same problem).

Also should we try to make book examples to actually run? If we don't then they can easily get stale.

**Comment by torkleyy** [comment]
I think it would be nice, but it's not strictly required; we've had no breakage for a while and current breaking changes are very small.

**Comment by oraknabo** [comment]
I can take this on.
Should the examples include "extern crate"  declarations? I at least put one in the final, full code listing on each chapter.

I see some minor issues in the text but I'll make separete issues for those and just focus on the formatting first.

**Comment by torkleyy** [comment]
> Should the examples include "extern crate" declarations? I would at least put one in the final, full code listing on each chapter.

If you think they're useful, feel free to add them. I highly appreciate efforts to improve the Specs book, thank you!

**Comment by torkleyy** [comment]
@oraknabo Do you still intend to format the chapters? This is kind of low priority and the default formatting changes every two weeks anyway. Otherwise I'd close this until there's a stable rustfmt version and probably also a better strategy to test examples written in Markdown.

**Comment by Rhuagh** [comment]
This should be closed.
