### ISSUE TITLE
[Bug] Dispatcher doesn't handle chained system dependencies

### ISSUE THREAD

**Issue by eldyer** [slide-rs/specs#253]
In a dispatcher with a system dependency chain built like this:

    let mut dispatcher = DispatcherBuilder::new()
        .add(A, "sys_a", &[])
        .add(B, "sys_b", &["sys_a"])
        .add(C, "sys_c", &["sys_b"])
        .build();

systems don't (always) run in the correct / expected order, which would be A, B, C in this case, since C depends on B which depends on A.

Until fixed, this can be worked around by adding every dependency explicitly, in the example above with `.add(C, "sys_c", &["sys_b", "sys_a"]).`

**Comment by torkleyy** [comment]
It seems that shred wants to run B and C in parallel. Dunno why :thinking:
