### ISSUE TITLE
Draining iterator for storages

### ISSUE THREAD

**Issue by malleusinferni** [slide-rs/specs#264]
On occasion, I find myself writing code like this:

```rust
for (_, eid) in (&foo, &entities).join() {
    if let Some(bar) = bar.remove(eid) {
        // Do something with bar
    }
}
```

Or this:

```rust
// To reduce allocation costs, working_set is owned by the system struct
for (_, eid) in (&bar, &entities).join() {
    self.working_set.push(eid);
}

for eid in self.working_set.drain(..) {
    if let Some(bar) = bar.remove(eid) {
        // ...
    }
}
```

Both of these rub me the wrong way, especially the second pattern with its redundant loop and owned list of entities. It seems to me that this logic should be available as some kind of modifier on the usual iteration patterns, since the storage already maintains a list of which entities have its associated components.

What I'd like to be able to write is something like the following:

```rust
// Remove "bar" from all entities that have it
for bar in bar.drain() {
    // ...
}

// Remove "bar" only from entities that also have "foo"
for (_, bar) in (&foo, bar.drain()).join() {
    // Do something with bar
}
```

I brought this up earlier on IRC earlier. @kvark suggested the name "drain" and @Aceeri suggested implementing it as a new Storage type. I'm not convinced the latter makes sense but I'm open to more suggestions.

**Comment by Aceeri** [comment]
Alternative using the `check` method:
```rust
for (entity, _, _) in (&*entities, &foo, &bar.check()).join() {
    bar.remove(entity);
}
```

**Comment by malleusinferni** [comment]
Thanks for the example. My codebase is still on 0.7 until I can work on it long enough to update it.

I would still prefer to have a `drain()` option for flexibility's sake.
