### ISSUE TITLE
inserting into a NullStorage slot that already contains a value panics

### ISSUE THREAD

**Issue by Ralith** [slide-rs/specs#266]
This is due to [generic code accessing the slot to swap its contents](https://github.com/slide-rs/specs/blob/master/src/storage/mod.rs#L212). Since `NullStorage` contains a copy of the value anyway, perhaps it could just return a (useless) reference instead of panicing on `get_mut`?

**Comment by WaDelma** [comment]
Hmm... How would one create useless reference for it? It would need to return new useless reference everytime it's called otherwise we have to remove `DistinctStorage` implementation for it.

**Comment by Ralith** [comment]
Does `DistinctStorage` actually require that the references be distinct? I'm not sure how mutably aliasing a zero-sized type could possibly go wrong. If you want to play it safe, wrapping the value in UnsafeCell should make such shenanigans strictly kosher, shouldn't it?

**Comment by torkleyy** [comment]
https://github.com/slide-rs/specs/blob/master/src/storage/tests.rs#L610

Shouldn't this test fail?

**Comment by WaDelma** [comment]
Yeah wrapping it to `UnsafeCell` should work.

I think it would be UB if you create multiple mutable references and the zero-sizedness doesn't matter.

**Comment by torkleyy** [comment]
Well, we do not actually guarantee it is a ZST right now.

**Comment by Ralith** [comment]
Reviewing [the `UnsafeCell` docs](https://doc.rust-lang.org/std/cell/struct.UnsafeCell.html), it's not actually obvious to me that returning a reference would be strictly correct after all:
> it is up to the abstraction designer to ensure that no two mutable references obtained this way are active at the same time, and that there are no active mutable references or mutations when an immutable reference is obtained from the cell

**Comment by Ralith** [comment]
Perhaps the call could be guarded by a `mem::size_of::<T>() != 0` check? I feel like that'd be a pretty tidy work-around.
