### ISSUE TITLE
Entry API for `&mut Storage`

### ISSUE THREAD

**Issue by omni-viral** [slide-rs/specs#268]
It would be great to have API similar to to `HashMap`s [Entry API](https://doc.rust-lang.org/std/collections/hash_map/struct.HashMap.html#method.entry) for mutable `Storage`.

This common pattern
```rust
if let Some(component) = storage.get(entity) {
    component
} else {
    storage.insert(entity, create_component());
    storage.get(entity).unwrap()
}
```
will be reduced to less error prone
```rust
storage.entry(entity).or_insert_with(create_component)
```

**Comment by Aceeri** [comment]
What should we do in the case that the entity that you are trying to get the `Entry` of is dead?

**Comment by omni-viral** [comment]
Good question @Aceeri
The entry will have 3 variants: Occupied, Vacant, Dead. `or_insert` will return `Result` and dead entry will return `Err`
