### ISSUE TITLE
Create Parallel Benchmark

### ISSUE THREAD

**Issue by ghost** [slide-rs/specs#27]
We currently don't really have any ways of proving the benefits of our design. Benchmarks are always a good way, they will also help shake out race conditions and places where things become a bottleneck that were not expected (I suspect the scheduler waiting on threads could be problematic for example).

What I would suggest is
- Add an example that has 16 or more components
- And 30 or more `systems` that touch one component or another
  - This should be a mix of things pure readers, pure writers and ones that read and write multiple parts
- Creates 10K entities
  - Should be a mix of components, not all entities should contain ever component
- Include dynamic creation and deletion of entities
- The main-loop tracks how long the systems took to process and prints out a summary of how long it took to run N times, and how long each loop took.

**Comment by White-Oak** [comment]
Does the last points stands for counting how long all systems took or each separately?

**Comment by csherratt** [comment]
@White-Oak I was thinking just how long it took to run the outer loop, but if you know a way to break it down to each system that would be neat too. :D

**Comment by torkleyy** [comment]
This is still relevant.

**Comment by torkleyy** [comment]
Just noticed we have `parallel` which pretty much covers this.
