### ISSUE TITLE
saveload tracking issue

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#282]
* `WorldDeserialize` is missing a `new` function
* Both `World*` structs should only contain generic storages, e.g. `Deref<Target = MaskedStorage>`

cc @omni-viral

**Comment by omni-viral** [comment]
Adding `new` function should be easy. Mostly it's will be a copy of `WorldSerialize:new`.

**Comment by omni-viral** [comment]
I need an explanation about second point.

**Comment by torkleyy** [comment]
From Gitter:

> You see, ReadStorage is just
> ```rust
> pub type ReadStorage<'a, T> = Storage<'a, T, Fetch<'a, MaskedStorage<T>>>;
> ```

> Now we just have to make sure that the paramater can be borrowed as Storage with data storage being 
> ```rust
> Deref<Target = MaskedStorage<T>>.
> ```

> So I'd guess 
> ```rust
> STORAGE: Borrow<Storage<'a, T, D>>, T: Component, D: Deref<Target = MaskedStorage<T>>
> ```

**Comment by omni-viral** [comment]
Ah. This will just relax requirements. So you could put the `WriteStorage` instead of `ReadStorage` for example.

**Comment by omni-viral** [comment]
This was a long one PR
