### ISSUE TITLE
Usage with NPhysics2D?

### ISSUE THREAD

**Issue by moonheart08** [slide-rs/specs#289]
Using the NPhysics world as a resource doesnt work (no send trait on 1 quintillion diffrent objects), what is the most efficient way to do it then?
I want it to be usable, in some way, as a resource. If thats not possible, then RIP me.
Also, if necessary, im fine with locking it (restricting parallelness), because it should only be used under special circumstances (like transforming a entity)

**Comment by torkleyy** [comment]
Hello @moonheart08! Nphysics is not optimal to use together with ECS, see https://github.com/sebcrozet/nphysics/issues/71 . AFAIK the maintainer is interested in making it more compatible. However, I know that it is possible to use nphysics and Specs together, @Ralith did that, maybe they can tell you how.

Also, there's another physics library developed right now which is specifically created for Specs: https://github.com/Rhuagh/rhusics

Hope that helps!

**Comment by moonheart08** [comment]
Thanks! 
Only issue is rhusic's lack of docs... Makes it hard to figure out what functionality it has.

**Comment by Ralith** [comment]
Using nphysics with specs is actually quite simple. The key caveat is that you can't expose any nphysics objects directly. The approach I used was to create a system to step the nphysics world, run it using [RunNow](https://slide-rs.github.io/specs/specs/trait.RunNow.html), and have its `System::run` impl copy the state you care about out of nphysics and into your entities and/or resources. You can store an entity ID (for example) in the rigid body user data field to simplify this, and keep a list of deleted entities each step so you can remove their bodies as well.

**Comment by moonheart08** [comment]
@Ralith Thanks a ton. Closing due to solved.
