### ISSUE TITLE
Custom drop function for components.

### ISSUE THREAD

**Issue by omni-viral** [slide-rs/specs#292]
It can help with optimizations if one could specify a function in `World::register<T>` as `FnMut(&mut World, T)` which would receive components of deleted entities during `World::maintain`.

For example resource releasing can be done with less overhead if you have `&mut` access to resource pool in comparison with what you can do if you have to release it in `drop` implementation.

**Comment by torkleyy** [comment]
Could you lower the level of abstraction and tell me what you're trying to implement? ;)

**Comment by omni-viral** [comment]
I'm implementing a `Buffer` - wrapper  for `gfx_hal::Backend::Buffer` that will deallocate it in the `Drop`.
But such deallocation will require some non-trivial synchronization since wrapper can only contain `Arc<SyncAllocator>` thus can deallocate in parallel with other buffers.
I want to provide the wrapper with special destruction method `Buffer::destroy(self, &mut Allocator)` which will perform deallocation in more efficient way.
But to call `Buffer::destroy` I need access to `Buffer`s that aren't needed anymore.
I'd like to provide a function to call `Buffer::destroy` to `World::register<Buffer>` or additional function like `World::register_with_drop` (naming suggestions are welcome)

**Comment by torkleyy** [comment]
@omni-viral But then we'd need the special drop in `amethyst_assets`, since we only have handles as components.

**Comment by torkleyy** [comment]
Closing because it's out of the scope of Specs: https://github.com/amethyst/amethyst/pull/442
