### ISSUE TITLE
No way to obain a `RestrictStorage` for `&Storage`

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#295]
The `restrict` method takes `&mut self`, even though there should be an immutable variant.

cc @Aceeri

**Comment by Aceeri** [comment]
I'm not sure if there is any point to having an immutable `RestrictStorage`, what would be the usecase?

**Comment by torkleyy** [comment]
You could get an entry and then later get the component without another check and without any `unwrap`.

**Comment by Aceeri** [comment]
True, I suppose I wasn't thinking entirely about the checks with the decision to not add immutable entries.
