### ISSUE TITLE
Good 2d collision detection to use with Specs

### ISSUE THREAD

**Issue by moonheart08** [slide-rs/specs#298]
I don't need a full featured physics engine (I need to write a domain specific physics engine), but i cant find a good collision detection library that works with Specs and is moderately fast. 
This is, obviously, a question.

Thanks in advance!

**Comment by minecrawler** [comment]
Have you checked out [Rhusics](https://github.com/Rhuagh/rhusics) and how it makes use of [collision-rs](https://github.com/kvark/collision-rs), yet?

**Comment by moonheart08** [comment]
Damn, I forgot about it (again)
I'll poke collision-rs a bit.

**Comment by torkleyy** [comment]
cc @Rhuagh

**Comment by Rhuagh** [comment]
https://github.com/Rhuagh/amethyst-rhusics

**Comment by torkleyy** [comment]
@moonheart08 Did `rhusics` work for you?

**Comment by moonheart08** [comment]
Works OK for testing. I'll be replacing it with a DSPE (Domain Specific Physics Engine) later, tho.
