### ISSUE TITLE
Parent-Child Entity Relationships

### ISSUE THREAD

**Issue by li3** [slide-rs/specs#300]
I have a couple situations where I would like to model a parent-child relationship with my entities. Say for example a turret module attached to another entity. But I'm not sure the best way to go about it in specs.

Any suggestions?

Thanks in advanced!

**Comment by OvermindDL1** [comment]
If it is a 1 parent to many children, I'd just put a component that holds an entityid to the parent, and put that component on the children (potentially add a positional offset in there too or data about why/how they are parented, etc...).

Think of ECS components like a SQL Database Table setup, same patterns.

**Comment by li3** [comment]
Hey thanks, that worked well.
