### ISSUE TITLE
`Storage::check` should return a reference

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#304]
While the original idea was that you could iterate over certain entities while still being able to borrow a storage inside, it's also useful to just get a bitset with the contained components. Thus, I'd suggest we return a reference and make cloning explicit.

**Comment by Aceeri** [comment]
Maybe we should just change it to `mask` or something?

**Comment by torkleyy** [comment]
Well you can also just do

```rust
for (pos, vel, _) in (&pos, &vel, (&bitset, &other_filter, &other_component)).join() {
    println!("Pos: {:?}", pos);
}
```

`mask` is a better name, yes. Let's deprecate `check` and add `mask`.
