### ISSUE TITLE
Optional Components 

### ISSUE THREAD

**Issue by ghost** [slide-rs/specs#31]
It would be good if there was a way for functions to specify, all entities that contain `&A`, `&B` and give me `Some(&C)` if C is defined, but `None` otherwise.

``` rust
fn run_xxx(|a: &mut A, b: &B, c: Option<&C>|

);
```

**Comment by kvark** [comment]
I thought about adding this, but then - systems that do that can just use the custom `run` already. So this is kinda low priority.

**Comment by torkleyy** [comment]
This issue doesn't apply anymore.
