### ISSUE TITLE
Add docs to the book how to retrieve a component for a given entity

### ISSUE THREAD

**Issue by tomc1998** [slide-rs/specs#310]
Hey!

So, unless I'm seriously misunderstanding something here, these types are mismatched!

Is there any reason why world doesn't use Index, and Index is not a usize?

To be clear, here is the `read_with_id()` method:

https://docs.rs/specs/0.10.0/specs/struct.World.html#method.read_with_id

And here is the Entity's `id()` method:

https://docs.rs/specs/0.10.0/specs/struct.Entity.html#method.id

Here is the definition of the `Index` typedef:

https://docs.rs/specs/0.10.0/specs/type.Index.html

I'd want to try & fix this myself, but i'm so new to the library I'm worried it's a misunderstanding - plus I wouldn't know whether to go with usize / u32, do you have any pointers?:P

**Comment by tomc1998** [comment]
So, I just cloned and changed the world method to take an Index then changed Index to a usize, and was met with loads of compile errors - is there a reason for this discrepancy, or is it just a bit messy? (i.e. should I even bother trying to clean up or is there a deeper reason they're different here)

**Comment by tomc1998** [comment]
Nevermind, figured it out. The 'id' is referring to a component id.

**Comment by torkleyy** [comment]
Yes you could basically have multiple component storages of the same type, which is useful for sceipting. Let's reopen it so the docs get improved.

**Comment by Rhuagh** [comment]
Is this still relevant?

**Comment by torkleyy** [comment]
@Rhuagh I'm not sure. If you're reading the book very closely you can see how to do it, but it should be more obvious I think. Probably worth its own chapter together with how relationships shall be modeled.

**Comment by Rhuagh** [comment]
What I was getting at here is that this ticket refers to a feature that no longer exists (`read_with_id`).

**Comment by Xaeroxe** [comment]
I concur with @Rhuagh , the ambiguity no longer exists because the function that caused confusion has been removed.

So I'll close this
