### ISSUE TITLE
Document that fetching both ReadStorage and WriteStorage isn't allowed

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#314]
@Xaeroxe wrote in a previous PR review:

> We should probably also add a more formalized way of saying: If you're retrieving both a WriteStorage and a ReadStorage for a component at the same time you're doing it wrong and your code won't work. (That's a common mistake I see people making)

**Comment by WaDelma** [comment]
We can probably draw parallel to Rusts default borrowing behaviour.
