### ISSUE TITLE
IndexedParallelIterator impl for JoinParIter

### ISSUE THREAD

**Issue by HybridEidolon** [slide-rs/specs#317]
It would be convenient to have a way of iterating only over some subset of matched tuples in a parallel join e.g.

```rust
// only process up to 32 entities matched
const MAX_PROCESSED_PER_TICK: usize = 32;
(&component_a, &component_b).par_join().take(MAX_PROCESSED_PER_TICK).for_each(do_thing)
```

**Comment by WaDelma** [comment]
I looked at possibility of implementing `IndexParallelIterator` when I was implementing `par_join`, but I don't think it's possible as there is no way that I know to cheaply index `BitSet` which is used to filter joined entities.

**Comment by torkleyy** [comment]
Sounds like the only workaround would be to iterate the components, take the first 32, collect them and then process that @HybridEidolon

**Comment by torkleyy** [comment]
Err..well not sure how to proceed here, any suggestions?

**Comment by Rhuagh** [comment]
I don't think its possible to cheaply do indexing on `BitSet`, which kind of breaks this.
