### ISSUE TITLE
EntitiesRes should provide a (lazy) entity builder

### ISSUE THREAD

**Issue by trsoluti** [slide-rs/specs#319]
For convenience and readability, I recommend Entities (EntityRes) provide an entity builder that looks to the outside world to be the same as the one used for World::create_entity(). Internally it would call the lazy updater to link the components.

This would allow a similar pattern to be used to create entities inside and outside Systems.

The user's code would look something like this:

```
entities.create_entity(&lazy_update)
        .with(mesh.clone())
        .with(background.clone())
        .with(component.clone())
        .with(local_transform)
        .with(Transform::default())
        .build()
```

**Comment by torkleyy** [comment]
I would love to add that, but unfortunately that's not possible. If you look at `EntityBuilder`, you can see that we need access to all the resources in order to the building. If `Entities` needs to provide such a method, it needs access to all the storages you're going to access.

**Comment by trsoluti** [comment]
I'm not sure what you mean by needing access to all the resources. The code calling create_entity() and with() has access. lazy_update doesn't need access as it's just queuing requests to world.maintain().

The sample code I wrote above would be equivalent to the following code:

```
let entity = self.create();
lazy_update.insert(entity, mesh);
lazy_update.insert(entity, background);
lazy_update.insert(entity, component);
lazy_update.insert(entity, local_transform);
lazy_update.insert(entity, Transform::default());
return entity
```
I'm doing this on a current Amethyst project and it's working properly.

**Comment by torkleyy** [comment]
Ah sorry, I missed the part where you said it should be done lazily. In that case, it is indeed possible.

**Comment by torkleyy** [comment]
I'm not sure why I missed it, you made it pretty obvious.
