### ISSUE TITLE
Does Storage need to hold the generation?

### ISSUE THREAD

**Issue by csherratt** [slide-rs/specs#32]
Right now both storage types hold a generation with the data. This is used to validate if the value in the `get/get_mut` is the same one being referenced.I think the check is needed, the question is do we need to make every storage track this state?

Currently, entities are only created by systems using the dynamic create functionality. Deletes are done lazily via the dynamic delete. Because the deletes are lazy the `entity index` is never reused twice between a `planner.wait()`. And since the deletes are done by the `specs` itself, we are guaranteed that the value will be removed during a `.wait()`.

Because of this design I think it is reasonable to assume
1) no `Storage` will actually be storing a value that is out of date with the generation
2) `specs` only needs a single place that holds the `latest` generation.

What I purpose, is we remove the generation from `Storage` and return every `Storage` wrapped in a magic type that joins the shared generation count with the type. This will implement `get` ect but will validate that the object is both alive and that the generation is correct. The storage trait would be simplified a bit by referring to each `get/insert/remove` by Index rather then by Entity.

This will reduce the size of the components in the `VecStorage` `HashMapStorage` which should mean they will work faster since it is less cache pressure.

**Comment by kvark** [comment]
> Currently, entities are only created by systems using the dynamic create functionality.

No, the world still has `create_now` method that can technically be called at any point where the world is available.

**Comment by kvark** [comment]
There is a tiny problem. If we require the read lock of `generation` vector for any operations on any storage, there is no way we can implement `CreateEntityIter` as it is now. This iterator needs to modify the generations as it yields more entities.
