### ISSUE TITLE
How to properly import specs_derive?

### ISSUE THREAD

**Issue by itmuckel** [slide-rs/specs#330]
Hey!
I want to use the macros from specs_derive, but in the book there is no information on how to include it.
I added the crate in my cargo.toml, but when I include it with `extern crate` in my top module, I get strange errors:

> warning: proc macro crates and `#[no_link]` crates have no effect without `#[macro_use]`

Adding `#[macro_use]` above `extern crate specs_derive;` and moving those lines to the top of my lib-file creates even weirder errors. The compiler complains, that it cannot find `Component`, although I include it from specs.

Can anyone give me detailed instructions on how to add `specs_derive` to an already compiling and working specs project? :-)

**Comment by torkleyy** [comment]
Please ensure that you have both crates added to your Cargo.toml and that you're declaring both `specs_derive` and `specs` in your crate. (the macro assumes the latter is available)

**Comment by torkleyy** [comment]
I'll explain in more detail if the above wasn't helpful.

**Comment by itmuckel** [comment]
I still get:
```
error[E0433]: failed to resolve. Did you mean `game::entities::specs`?
  --> src\game\entities.rs:21:10
   |
21 | #[derive(Component, Debug)]
   |          ^^^^^^^^^ Did you mean `game::entities::specs`?
```

On top of `entities.rs` I have:
```rust
extern crate specs;
extern crate ggez;

use self::ggez::graphics::Point;
use self::specs::{
    DispatcherBuilder,
    Join,
    Component, // <----
    System,
    World,
    Fetch,
    ReadStorage,
    WriteStorage,
    VecStorage,
};
```

**Comment by torkleyy** [comment]
Try placing the crate declarations in your lib.rs or main
rs.

**Comment by itmuckel** [comment]
Aaaaaah! That did it! Of course `pub extern crate specs` needs to be placed in the same file as
```rust
#[macro_use]
pub extern crate specs_derive;
```
otherwise `specs_derive` has nothing to operate on. 😄 

Thank you very much for your help and this sweet library!

**Comment by torkleyy** [comment]
Glad it works now for you :)
