### ISSUE TITLE
thread 'main' panicked at 'No resource with the given id'

### ISSUE THREAD

**Issue by itmuckel** [slide-rs/specs#331]
I have the following code:
```rust
    fn update(&mut self, _ctx: &mut Context, _dt: Duration) -> GameResult<()> {
        self.update(InputEvent::None);
        self.dispatcher.dispatch(&mut self.world.res);

        Ok(())
    }
```
dispatcher is a `Dispatcher<'static, 'static>` and world is a `World`.

Here's the StackTrace:
thread 'main' panicked at 'No resource with the given id', src\libcore\option.rs:874:4
stack backtrace:
```
   0:     0x7ff6e9dbfa8d - std::sys::windows::backtrace::unwind_backtrace
                               at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1:     0x7ff6e9db8077 - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:68
   2:     0x7ff6e9db5da3 - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:383
   3:     0x7ff6e9db58ec - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:397
   4:     0x7ff6e9db6385 - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:577
   5:     0x7ff6e9db6190 - std::panicking::begin_panic<alloc::string::String>
                               at C:\projects\rust\src\libstd\panicking.rs:538
   6:     0x7ff6e9db60e1 - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:522
   7:     0x7ff6e9db6059 - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:498
   8:     0x7ff6e9dcca1c - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:71
   9:     0x7ff6e9dccdca - core::option::expect_failed
                               at C:\projects\rust\src\libcore\option.rs:874
  10:     0x7ff6e9c5794b - shred::system::{{impl}}::run_now<plan_col::game::entities::MoveToDestination>
                               at C:\Users\itmuckel\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.5.1\src\system.rs:25
  11:     0x7ff6e9c6b36c - shred::dispatch::dispatcher::Dispatcher::dispatch
                               at C:\Users\itmuckel\.cargo\registry\src\github.com-1ecc6299db9ec823\shred-0.5.1\src\dispatch\dispatcher.rs:33
  12:     0x7ff6e9c6155e - plan_col::run
                               at C:\Users\itmuckel\Documents\TEMP\Rust\plan_col\src\lib.rs:15
  13:     0x7ff6e9dc92a1 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:101
  14:     0x7ff6e9db0fbb - std::rt::lang_start
                               at C:\projects\rust\src\libstd\rt.rs:50
  15:     0x7ff6e9ddc413 - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  16:     0x7ffc667b1fe3 - BaseThreadInitThunk
```

Without the call to dispatch the program runs, but is of course useless. 😆 

In the docs it says that `dispatch` panics, when resources are borrowed, but I don't think I have done something like that. What resources is this about?

Any ideas?

**Comment by torkleyy** [comment]
Yes, this is a common problem. You forgot to register a component or add a resource. The code has already been improved to debug the problem, you can use the master branch and enable the nightly feature to do that.

**Comment by itmuckel** [comment]
No, this is a different error. I also had the error with the new improved error message. I added all Components I use and now I get only the error 'No resource with the given id'.

Before it was: `No component with the given id. Did you forget to register the component with 'World::register::<ComponentName>()'?`, now the additional information is missing.

**Comment by torkleyy** [comment]
No, this isn't the improved error messsge. I think you forgot to add a resource. How many systems are you using? Check which resources you're asking for there.

**Comment by itmuckel** [comment]
Oh yes, you were right! I had a system operating on a resource, that I didn't add to my Entity, so I thought it was okay to not register it. 

Of course every component and resource has to be registered in the world, when there is a system using it. 

My bad. But it would be useful to get an error message for missing resources too, right?

**Comment by torkleyy** [comment]
Yes, I think that's been added. But let's leave the issue open and I'll check once I'm at home (could also improve docs to make it more obvious how to debug). If you have more questions, you can also use the Gitter channel which is linked to from the README.

**Comment by torkleyy** [comment]
Mainly we have to check if everything is working and add a troubleshooting section to the book.

**Comment by Rhuagh** [comment]
I believe this has been addressed by the new setup system, and there's also a much improved error message if you run with the nightly feature on shred (pending a PR there). 

Most of this should be described in the book already ?
