### ISSUE TITLE
Get entities sorted by component value

### ISSUE THREAD

**Issue by itmuckel** [slide-rs/specs#333]
Is there a way to get entities sorted by a component?

<h4>Use case</h4>

I have the following code in my drawing loop:
```rust
let graphics_id = self.world.read::<entities::GraphicsID>();
let draw_params = self.world.read::<entities::DrawParameters>();

for (gid, draw_params) in (&graphics_id, &draw_params).join() {
    graphics::set_color(ctx, graphics::WHITE)?;
    graphics::draw_ex(ctx,
                      self.asset_manager.get_graphics_component_for(gid.0).image(),
                      draw_params.0)?;
}        
```

Now every entity has a component:
```rust
pub struct ZIndex(pub u32);
``` 

Is there a way to read out all entities sorted by this component? I want to make sure that the components are drawn sorted by their z-index.

**Comment by torkleyy** [comment]
I see two ways to do it. The easy way would be collecting the whole thing and sorting it:

```rust
let mut params: Vec<_> = (&graphics_id, &draw_params).join.collect();
params.sort_by(..);
```

Another approach would be to maintain a cache of the draw order (e.g. by keeping a `Vec` of entities) and maintaining that cache by modifying it according to the changes made on the component storage.

I have an experimental API on master for this (`TrackedStorage`) and @Aceeri is currently replacing it in https://github.com/slide-rs/specs/pull/311

So the first approach is probably easier for you :)

**Comment by itmuckel** [comment]
Yes, nice, didn't know you could collect that.  😃 

As a side note:
I'm still very new to the concept of ECS. I'm programming a game in my free time since three months and the code looked horrible, because I tried to apply OO techniques. With specs the code looks so much cleaner and is easier to modify and extend. Mind blown.

**Comment by torkleyy** [comment]
This should go into the book before closing.
