### ISSUE TITLE
API to create entities with Id and to retrieve them via Id

### ISSUE THREAD

**Issue by 0nkery** [slide-rs/specs#338]
Hi, thanks for awesome library!

I'm working on multiplayer client/server game. Would be awesome to have an API to create entities with specific Id (since all entities managed by server and server assigns Ids to them) and retrieve them via specific Id (e.g. to apply updates coming from server).

Currently I'm using `NetworkId` component and sending updates from server in `map<Id, Update>`. For player character entity I created `Controllable` flag-component which helps to find the entity I need.

But it doesn't feel right. Maybe there is a better way to design such system using tools already provided? Or maybe you'll consider to add APIs I described?

**Comment by torkleyy** [comment]
What you're doing sounds pretty good already! Networking is a common thing, so I do want to have this in Specs. And the good news is that there already is something: the `saveload` module created by @omni-viral. It's a really great start for this, but lacks some docs and has some limitations currently, thus I started working on [an overhaul in this PR](https://github.com/slide-rs/specs/pull/337). I think I can finish it tomorrow if I don't forget it.

**Comment by 0nkery** [comment]
Thanks for reply. I suppose it's unreleased so I'll til release. :)
