### ISSUE TITLE
Module structure: revise, fix links and imports

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#351]
* [x] The book is currently using the wrong imports
* [x] The crate-level docs link to several items that do not exist anymore
* [x] `bitset` is public, but doesn't expose anything
* [x] Check if the `prelude` contains everything important, but not too many items

**Comment by jojolepro** [comment]
I liked it a lot when most of the stuff was exported at the root of the project. It made it easy to add a single import, without having to precise which module it is stored in. I think prelude is good to quickly test something, by using specs::prelude::*, and the root export was good for quick developement, without the need to import specs::*

**Comment by Rhuagh** [comment]
I believe all of these are fixed now?

**Comment by jojolepro** [comment]
The only missing import I saw was specs::storage::NullStorage
;)

**Comment by Rhuagh** [comment]
Care to add a PR ?

**Comment by torkleyy** [comment]
@GraemeWilde Opening another issue for it.
