### ISSUE TITLE
Networking with specs?

### ISSUE THREAD

**Issue by moonheart08** [slide-rs/specs#360]
Just a simple question, but how would networking be done in a sane, clean manner with specs?

**Comment by torkleyy** [comment]
There's no really nice way in the released version, but it's being worked on. The last step is to merge https://github.com/slide-rs/specs/pull/337. It's basically close to ready, only the review comments have to be addressed.

**Comment by torkleyy** [comment]
@moonheart08 If you want to, you can already try it out with `0.11-alpha4`. It would be really cool if you could give us some feedback :)
