### ISSUE TITLE
another storage to help synchronizing with external storage

### ISSUE THREAD

**Issue by thiolliere** [slide-rs/specs#361]
I use specs with nphysics (actually a fork on my own but 0.8 nphysics will impl things..) I have to synchronize RigidBodyHandle in specs world and in nphysics world.

My needs are:
* for insert everything is sync: the method to create RigidBodyHandle component takes nphysics world and create them altogether
* for remove I accept that some object are still alive in nphysics world but have no component in specs. and then I want to regularly sync things by removing those objects that have been deleted from specs world. But to do so I have issues:

I tried to implement using flagged storage in current master but I can't get the deleted component I just have the index of the entity deleted and that is not enough:
```rust
extern crate specs;

use specs::prelude::*;

#[derive(Debug)]
struct Vel(usize);

impl Component for Vel {
    type Storage = FlaggedStorage<Self, VecStorage<Self>>;
}

fn main() {
    let mut vels = vec![];
    let mut world = World::new();
    world.register::<Vel>();
    let mut removed_id = world.write::<Vel>().track_removed();

    vels.push(0.0);
    let e0 = world.create_entity().with(Vel(0)).build();

    {
        // remove an entity
        println!("entity removed:  {:?}", e0);
        world.delete_entity(e0).unwrap();

        // add an entity
        vels.push(0.3);
        let e1 = world.create_entity().with(Vel(1)).build();
        println!("entity created:  {:?}", e1);

        // try to find removed component
        let mut removed = BitSet::new();
        world.write::<Vel>().populate_removed(&mut removed_id, &mut removed);

        let entities = world.entities();
        for (e, _, v) in (&*entities, &removed, &world.read::<Vel>()).join() {
            // this does show we found new component instead
            println!("component of removed ? {:?}: {:?}", e, v);
        }
    }
}
```

The solution I'll implement is to create a new storage that keeps deleted component in some cache that I'll clear regularly (with removing their nphysic body).
This implementation is straightforward but might be needed by others so that is why I open this issue and also to know if you have better solution.

**Comment by torkleyy** [comment]
There's no too obvious solution as far as I can tell with my limited knowledge of nphysics.

I think I need some more information to give a good recommendation. I'll look into it later.

**Comment by thiolliere** [comment]
I don't think it is  related to nphysics, in my example I use an external storage of velocities.

The solution I found is to have a new storage like `FlaggedStorage` but without tracker field and with `cache: Vec<C>` field with remove method inserting a clone of component into cache (this requires that component is clonable) and a method to get access to cache.

**Comment by torkleyy** [comment]
Well I think your solution is a pretty solid one, don't see any issues with it.

**Comment by thiolliere** [comment]
Yes I actually opened the issue because synchronizing with external storage can be a standard pattern. But this kind of RetainedStorage may be specific to nphysics or physic engine in general that allow incoference such as present in physic world but absent in specs world until next manual maintain.

then I don't know about this pattern in general, maybe it should be addressed specifcally.

This issue was more about showing a solution to a specific instance of this pattern. Feel free to close it

**Comment by WaDelma** [comment]
As inserting to cache happens only when the components are removed, it should be possible to not do any clones, right? Or am I missing something.

**Comment by torkleyy** [comment]
The API requires you to return the removed component.

**Comment by WaDelma** [comment]
Ah that would prevent it then. We could probably change remove to return associated type which storages could use to change the behaviour, but that would be overkill.

**Comment by torkleyy** [comment]
Yeah, that would complicate generic code a lot.

**Comment by thiolliere** [comment]
usually when you work with an external storage the spec component is just a handle, cloning it is very usually very cheap.

**Comment by Rhuagh** [comment]
Adding a cache type system is certainly possible, but connecting that to the logic is much harder to do generically. The basic problem is that you can't update the cache in separation, you need to update the cache in lock step with the sync logic, otherwise you're back in the same rabbit hole.

**Comment by andrewhickman** [comment]
What about adding a way to send data along with the TrackedStorage events? This could be a clone of the component, some kind of unique id or just `()`.

Rough sketch: add a trait
```
trait TrackData<C: Component> {
    fn new(component: &C) -> Self;
}

impl<C: Component> TrackData<C> for () {
   fn new(component: &C) -> Self { () }
}
```

Then add a type parameter to `FlaggedStorage` defaulting to `()` that defaults to `()`.

**Comment by andrewhickman** [comment]
Another issue I've run into with synchronising with external storages is that if you are reading both the `insert` and `remove` event channels then you cannot tell which order the events came in. It is possible to get multiple `InsertFlag`s and `RemovedFlag`s for the same component, which makes it awkward to work out whether the component ended up being added or removed.

**Comment by Rhuagh** [comment]
Process remove first, then insert. If you read every frame it's safe.

**Comment by andrewhickman** [comment]
What do you mean by 'safe'?

**Comment by andrewhickman** [comment]
What version of specs are you testing? My test code is below, and it prints several add and removed events.

```
extern crate specs;

use specs::prelude::*;

pub struct Comp;
impl Component for Comp {
    type Storage = FlaggedStorage<Self>;
}

pub struct CompSystem {
    inserted_id: ReaderId<InsertedFlag>,
    removed_id: ReaderId<RemovedFlag>,
}

impl<'a> System<'a> for CompSystem {
    type SystemData = WriteStorage<'a, Comp>;

    fn run(&mut self, comps: Self::SystemData) {
        for event in comps.removed().read(&mut self.removed_id) {
            println!("removed: {:?}", event);
        }

        for event in comps.inserted().read(&mut self.inserted_id) {
            println!("inserted: {:?}", *event);
        }
    }
}

pub struct AddRemoveSystem(Entity);

impl<'a> System<'a> for AddRemoveSystem {
    type SystemData = WriteStorage<'a, Comp>;

    fn run(&mut self, mut comps: Self::SystemData) {
//        comps.insert(self.0, Comp);
        comps.remove(self.0);
        comps.insert(self.0, Comp);
        comps.remove(self.0);
        comps.insert(self.0, Comp);
        comps.remove(self.0);
    }
}

fn main() {
    let mut world = World::new();
    world.register::<Comp>();

    let mut ar_sys = AddRemoveSystem(world
        .create_entity()
        .with(Comp)
        .build()
    );

    let mut comp_sys = {
        let mut comps = world.write_storage::<Comp>();
        CompSystem {
            removed_id: comps.track_removed(),
            inserted_id: comps.track_inserted(),
        }
    };

    ar_sys.run_now(&mut world.res);
    comp_sys.run_now(&mut world.res);
}
```

**Comment by GraemeWilde** [comment]
0.11, but using the storage.populate_{insert/removed/modified} like in the examples, I think that might be your issue.

**Comment by andrewhickman** [comment]
Are you using a bitset with populate_{insert/removed/modified}? That would explain why you get only one event for each index

**Comment by GraemeWilde** [comment]
Yep

**Comment by andrewhickman** [comment]
Can I take a look at your code? When I insert, then remove I still get both events.

**Comment by GraemeWilde** [comment]
It's not a simple test, so it's not tiny.
https://pastebin.com/aDctj9aQ
The relevant code is in the `impl<'a, S> System<'a> for ZSortSystem<ZComponent<S>>`, and there is a test in there I'm using to check it. Run the tests with `cargo test -- --nocapture` or the `println`s in the test won't show up.

**Comment by andrewhickman** [comment]
I think the reason you get that behaviour is you join over the entities resource when you go through insertions, so you don't see insert events for entities that no longer exist.

**Comment by andrewhickman** [comment]
I've published a crate [specs-mirror](https://crates.io/crates/specs-mirror) to hopefully help with this use-case. I've designed it with my own use case in mind but it should work with something like nphysics with a bit of tweaking.

**Comment by GraemeWilde** [comment]
> I think the reason you get that behaviour is you join over the entities resource when you go through insertions, so you don't see insert events for entities that no longer exist.

Taking out entities still gives the same result for me.

I gave it a try with your code, replacing the CompSystem impl with:
```
impl<'a> System<'a> for CompSystem {
    type SystemData = WriteStorage<'a, Comp>;

    fn run(&mut self, comps: Self::SystemData) {
        let mut removed = BitSet::new();
        let mut inserted = BitSet::new();

        comps.populate_removed(&mut self.removed_id, &mut removed);
        comps.populate_inserted(&mut self.inserted_id, &mut inserted);

        for index in &removed {
            println!("Removed: {}", index);
        }

        for index in &inserted {
            println!("Inserted: {}", index);
        }
    }
}
```
Outputs:
```
Removed: 0
Inserted: 0
```
So that seems to be working as expected for me, I'm not sure why it's not working for you :(

**Comment by torkleyy** [comment]
Is there anything that needs to be fixed?

**Comment by torkleyy** [comment]
I skimmed through this issue and there seems to be some confusion about the `FlaggedStorage`. Events get pushed once they come in, so there's definitely no way for them to disappear.

Huh, at the moment I'm myself unsure how you need to process them..

**Comment by torkleyy** [comment]
I've added a PR that is going to demonstrate how you keep track of the inserted components. Right now I don't know how it was done, and I couldn't find any examples in Amethyst. I hope this isn't some oversight.

**Comment by torkleyy** [comment]
The proposed storage is implemented in https://crates.io/crates/specs-mirror, closing.
