### ISSUE TITLE
ParJoin is not implemented for AntiStorage

### ISSUE THREAD

**Issue by WaDelma** [slide-rs/specs#364]
If you try to convert [example](https://slide-rs.github.io/specs/07_join.html#excluding-components) in the book to use `par_join`:
```rust
(
    &*entities,
    &mut pos_storage,
    &vel_storage,
    !&freezed_storage,
).par_join().for_each(|(ent, pos, vel, ())| {
    println!("Processing entity: {:?}", ent);
    *pos += *vel;
});
```
It fails to compile because `ParJoin` isn't implemented for `AntiStorage`.
This seems to be oversight as `DistinctStorage` is implemented for it.

**Comment by Rhuagh** [comment]
Nevermind, it's the `Deref` to `MaskedStorage` that will make it miss.
