### ISSUE TITLE
Unused `InsertResult` does not generate a compiler warning.

### ISSUE THREAD

**Issue by Xaeroxe** [slide-rs/specs#385]
I've found code that wrongly assumes that after an insert has been called for an Entity that calling `storage.get(entity).unwrap()` is not going to panic.  This may panic because the Entity could have been dead for the insert.  Is it possible for us to generate a compiler warning for unused `InsertResult` similar to how rustc generates a compiler warning for unused `Result`?

**Comment by torkleyy** [comment]
Yep, with `#[must_use]`.
