### ISSUE TITLE
`EntityBuilder` should destroy entity if `build` wasn't called.

### ISSUE THREAD

**Issue by omni-viral** [slide-rs/specs#388]
subj

**Comment by torkleyy** [comment]
Hmm the builder should not be created in the first place then.. I can see why you'd want that though.

**Comment by adeschamps** [comment]
Can this be made into a warning by adding the `#[must_use]` attribute to the builder?

**Comment by omni-viral** [comment]
I was trying to design a function to create an entity that takes `EntityBuilder` and returns it. But then in case of error the `Entity` will stay there.
After that I realized I can't make it anyway because I need to borrow resources from `World`.

**Comment by torkleyy** [comment]
There is `create_entity_unchecked` for that.

**Comment by torkleyy** [comment]
But yeah your case is exactly what I had in mind, but then there could also be an error after we called build, so the function returns an error and the Entity essentially gets leaked.

**Comment by omni-viral** [comment]
After calling `build` you have `Entity` and `World` to destroy it yourself.
