### ISSUE TITLE
Ideal systems API

### ISSUE THREAD

**Issue by kvark** [slide-rs/specs#40]
This is how I see our hypothetical API (forked from #30):

``` rust
trait System<C: Clone>: Send { //`C` stands for "Context"
    /// A composition of ECS components, some writeable, some not, that are processed.
    type<'a> Data<'a>: SystemInput; // it's a type that depends on arbitrary lifetime 'a (HKT)
    /// Fetch the required components from the world.
    /// May block until the components become available.
    fn fetch<'a>(&self, &'a World) -> Self::Data<'a>;
    /// Main processing entry point, implemented by default to allow users to only 
    //// implement `on_each` and friends to get this automatically.
    fn run(&mut self, data: Self::Data, context: C) {
        self.on_start(context);
        for (ent, elem) in data.iter() {
            self.on_each(ent, elem);
        }
        self.on_finish();
    }
    fn on_start(&mut self, C) {}
    fn on_each(&mut self, Entity, Self::Data::Element) {}
    fn on_finish(&mut self) {}
}
```

Main concerns:
1. Currently impossible for the fact it needs HKT over lifetimes. Need to find a workaround, perhaps by erasing the lifetime of the locks, or using lower-level locks under the hood (`StaticRwLock`).
2. May need a way to communicate between `on_start`, `on_each`, and `on_finish`. With this design, the only way to pass data through is via `self`, but it's possible.
3. Need to automatically implement this trait for function closures that match `on_each` or `run` arguments. This may be non-trivial and require some magic dust.

**Comment by csherratt** [comment]
Rather then dealing with the fetch, can we just make the trait as lean as possible?

```rust
trait System<C: Clone>: Send { //`C` stands for "Context"
    /// Main processing entry point, implemented by default to allow users to only 
    //// implement `on_each` and friends to get this automatically.
    fn run(&mut self, world: &'a World, context: C);
}
```

implementing it is pretty much the current `run` function. Basically letting the user do the outer loop rather then trying to wrap it up into a trait.

**Comment by kvark** [comment]
@csherratt that may be a good intermediate state for us: we'd convert to traits, make the actual system objects to move between threads, and then keep our eyes open for any HKT advancements in the language. Now, why this would be nicer than just `run`:
  1. it would seamlessly allow users to implement `run_each` instead of `run` if they don't need all the control.
  2. it would enforce `fetch` to happen at compile time instead of run-time
  3. it would provide a simpler interface (no closures)

**Comment by torkleyy** [comment]
What parts of the proposed design do we still want? One advantage over just `run` might be that the system can do work which does not "lock" resources/components.
