### ISSUE TITLE
Consider ThreadPool alternatives

### ISSUE THREAD

**Issue by kvark** [slide-rs/specs#42]
I see 2 minor-ish issues with it:
1. the need to specify the number of threads
2. the overlapping logic of our systems going back and forth with their threads

**Comment by sinesc** [comment]
Would it at all be possible to use a scoped threadpool instead? I'm ending up with lazy statics everywhere.

**Comment by kvark** [comment]
@sinesc would be great!

**Comment by cjhowe** [comment]
If we do look at alternatives, it'd be nice if we could work to integrate it with rayon as well. I'm very interested in the ability to share thread pools between specs and rayon, especially since their use together seems to be very practical.

**Comment by torkleyy** [comment]
@kvark probably fixed by #125?

**Comment by kvark** [comment]
@torkleyy I suppose, yeah.
