### ISSUE TITLE
Document compatible shred version

### ISSUE THREAD

**Issue by sinesc** [slide-rs/specs#421]
It would be helpful if the library documention included a .toml example with the currently compatible shred, shred-derive, ... versions.
The error-messages generated by the compiler in case of an incompatibility don't make it entirely obvious what the actual problem is, e..g. I ran into issues where my system-data no longer satisfied the SystemData trait.

**Comment by torkleyy** [comment]
Let's add this to both the book and API docs.

**Comment by LinearZoetrope** [comment]
Alternate method: re-export `shred` and `shred-derive` from specs.

`serde` does this:
https://github.com/serde-rs/serde/blob/master/serde/src/lib.rs

For any non-macro crate you can do:

```
pub mod foo {
    extern crate foo;
    pub use foo::*;
}
```

For a macro crate you can do:

```
#[macro_use]
extern crate foo as _foo;
pub mod foo {
    pub use super::foo::*;
}
```

**Comment by schell** [comment]
And what versions *do* work?

**Comment by torkleyy** [comment]
The one used by the Specs version you're using. You can go to crates.io -> specs -> dependencies to see the correct shred version.
