### ISSUE TITLE
Implement common builder trait

### ISSUE THREAD

**Issue by sinesc** [slide-rs/specs#422]
It would be convenient to have a common builder trait for EntityBuilder and LazyBuilder, so entity-building code could be reused regardless of which builder is being used.

```rust
trait Builder {
    fn with<T: specs::Component + Send + Sync>(self, c: T) -> Self;
    fn build(self) -> specs::Entity;
}
```

The name should probably be a bit more specific.

**Comment by torkleyy** [comment]
@sinesc Thanks for the suggestion, I think there are even more things we could expose via traits, like inserting a component or similar.

**Comment by GraemeWilde** [comment]
You would need to `use` the new trait right? So would this be a breaking change?

**Comment by Aceeri** [comment]
@torkleyy Can close this issue by the way :)
