### ISSUE TITLE
Join::open should be unsafe

### ISSUE THREAD

**Issue by andrewhickman** [slide-rs/specs#428]
The following safe code segfaults for me

```
extern crate specs;

use std::mem;
use specs::prelude::*;
use specs::join::Join;

struct Comp(u32);

impl Component for Comp {
    type Storage = VecStorage<Self>;
}

fn main() {
    let mut world = World::new();
    world.register::<Comp>();

    world.create_entity()
        .with(Comp(5))
        .build();
    
    mem::replace(Join::open(&mut world.write_storage::<Comp>()).1, VecStorage::default());

    for comp in world.read_storage::<Comp>().join() {
        println!("{}", comp.0);
    }
}
```

`Storage::unprotected_storage_mut` should also be unsafe. I think `Storage::unprotected_storage` is still safe.

**Comment by Xaeroxe** [comment]
Nice catch.  Strictly speaking it's not that `Join::open` is unsafe, but rather our implementation of `Join` for `Storage` resulted in false assumptions elsewhere.  We exposed too much access to our internals.  I think we should review the API and find places where the storage can have entries added or removed without making the necessary changes to the bitset.  This is one of them.

**Comment by Xaeroxe** [comment]
So after a thorough review of the API these were the only errors of this sort that I could find.

And after putting a fair amount of thought into alternatives I actually agree with @andrewhickman 's original proposal.  These should be marked unsafe.  I think so for the following reasons

- There are other ways to get the bitset immutably.
- End users should never have access to mutable `Join::Value` in a safe context.  There's just too much hazard here.
- Allowing "safe if immutable but unsafe if mutable" APIs here complicates the API in undesirable ways,
