### ISSUE TITLE
Implement a way to have `setup` dependencies

### ISSUE THREAD

**Issue by Xaeroxe** [slide-rs/specs#438]
Some systems rely on the output from another system's `setup` function before they can run their own `setup` function.  We need some way of communicating these dependencies to the Dispatcher.

**Comment by Xaeroxe** [comment]
Ok, but that means for most Amethyst users `MaterialDefaults` is useless during `setup`.

**Comment by torkleyy** [comment]
Phew, I don't know how to solve that honestly.

**Comment by torkleyy** [comment]
Closing; see #525
