### ISSUE TITLE
Book Hello World specs_derive

### ISSUE THREAD

**Issue by MrMonotone** [slide-rs/specs#441]
The book mentions that you can use specs_derive by just importing specs and then including spec_derive like so:
```
extern crate specs;
#[macro_use]
extern crate specs_derive;
```
However you have to also add specs_derive to the TOML file so: 
```
[dependencies]
specs = "0.12"
specs-derive = "0.2.0"
```

Is this an issue? Sorry I am new to rust and it took me awhile to figure it out. Maybe the tutorial should be updated or should specs expose specs_derive without the reference in the TOML file?

I should also mention that rls still complains that it cant find it even when I would it in the TOML, however, it still compiles???

**Comment by torkleyy** [comment]
When you add an extern crate line, you almost always need to add a line to your `Cargo.toml`, too. If you want to, you can add that to the book.

The rls issue sounds strange, but I can't help you here since I never used it. If it still doesn't work I recommend you ask for help there.

**Comment by MrMonotone** [comment]
Thanks I will just ignore the issue. This issue will be good enough reference for noobs like me lol
