### ISSUE TITLE
World::maintain() just deletes all entities?

### ISSUE THREAD

**Issue by tomc1998** [slide-rs/specs#442]
Hey!

So, this is either a bug or a docs issue. Here is how I expect World::maintain() to work:

* Create some entities dynamically
* Call world::maintain(), adds entities
* Call world::maintain() again, no changes
* Delete some entities dynamically
* Call world::maintain(), deletes entities
* Call world::maintain() again, no changes

Currently, it seems to just be deleting all my entities. Have I misunderstood how this works? Currently I don't know how to dynamically delete an entity, without also deleting all other entities in the world.

Thanks!

**Comment by Xaeroxe** [comment]
@tomc1998 Which methods are you using to delete entities?  It'll be helpful in tracking down this bug.

**Comment by tomc1998** [comment]
I'm using EntitiesRes::delete().

**Comment by tomc1998** [comment]
Hang on... I'm not calling build() on the entitybuilder!

That's crazy, because without a world::maintain call the entities do get added. Is there anything to add to make it very clear? This seems like it must be an easy mistake to make.

**Comment by tomc1998** [comment]
Hang on, looking at the source, why does calling build() even matter? all build() does is return the entity...?

**Comment by Xaeroxe** [comment]
Because otherwise we have no way of knowing when to return the entity.

**Comment by tomc1998** [comment]
No, i mean - my issue is fixed when I call build(), even though I immediately discard the returned entity.

It looks like when I call world::maintain(), it called the allocator::merge() function, which deletes the entity components I added UNLESS I call build() on the builder I'm using (even though all build() does it return the entity!)

**Comment by Xaeroxe** [comment]
Yeah that was specifically added in to make the builder behave more like a typical builder pattern.  Hang on I've got a fix for it I'm testing now.

**Comment by tomc1998** [comment]
Huh okay, weird...

Regardless, didn't even realise that annotation existed, awesome!

**Comment by omni-viral** [comment]
`build` also marks entity as `built`. Without it builder deletes entity when dropped.

**Comment by torkleyy** [comment]
Hm, I know we added this, but this really seems weird. Any idea to solve it @Xaeroxe ?
