### ISSUE TITLE
Help/suggestion to implement a "diff log" for components

### ISSUE THREAD

**Issue by Ploppz** [slide-rs/specs#444]
This issue can either be seen as a request for help in implementing it or a suggestion for a possible feature.

I am doing networking in my game, and I want to send a (partial) snapshot from the server to the client, of the game's state. "Partial" means it should exclude components that have not changed since the last snapshot that was sent to a client. (this could differ between different players). Note that while the server could have a tick rate of say 60, clients could want 20 packets per second, or less or more depending on their network bandwidth. (I am inspired by [this article](https://developer.valvesoftware.com/wiki/Source_Multiplayer_Networking) by Valve).

So an idea from the Gitter chatroom was to have an alternative to `WriteStorage`, called say `LoggerWriteStorage`. in a `System::run()` implementation, `join()` would make sure that the programmer's writes to a component are also processed so as to generate a "diff". Diff meaning just a collection of components that were changed that frame (by any number of systems). I imagine this would sort of be a transient ECS system with entities and all, but with only the components that have been written to, changed. I would need to store a diff for each frame, going back probably no more than one second in time. Then whenever I want to send a snapshot to a client, I can sum the diffs since the last time that client received a snapshot.

I have been looking at the source code for some time and starting to get an idea how some stuff works like Storage/WriteStorage, MaskedStorage, FetchMut. But I am not sure how I would go about making some LoggingWriteStorage which also writes to something owned by the Dispatcher. Because in normal operation, in a loop where you use .join(), you just get a `&mut T` (AFAIK by looking at the Join implementation on Storage).

How would I go about implementing such a thing? Any ideas for other ways to achieve this? Opinions whether this is worth pursuing are also welcome.

**Comment by Xaeroxe** [comment]
@Ploppz What you've described sounds a lot like `TrackedStorage`.  Does that help you at all?

**Comment by Xaeroxe** [comment]
https://docs.rs/specs/0.12.0/specs/index.html?search=track

**Comment by Ploppz** [comment]
Thanks! It's similar indeed. I think I can achieve the same by calling `populate_modified()` to store modifications for each frame separately.
Can I assume data integrity across several frames? With that I mean: If a bit is set in e.g. `modified: BitSet` in a frame, will this that bit still mean the same (point to the same component) X frames later?

**Comment by Ploppz** [comment]
It seems like BitSet actually can only track entities, not components; is this correct? I need component granularity. For example, the shape (polygon) of an entity never changes, so it should only be sent once to a client, while position changes all the time.
If this does not help me after all then no worries, I am thinking about a solution that could work well outside of Specs - it's not necessary to dig into it.

**Comment by Xaeroxe** [comment]
So there's a new `modified` bitset for each component type you use this storage with, which means that while yes it does indicate a component on a particular entity, it can still be narrowed down to one specific component.

**Comment by Ploppz** [comment]
Ah I see, thanks!

**Comment by torkleyy** [comment]
> will this that bit still mean the same (point to the same component) X frames later?

The bit that's set corresponds to the entity id. That means it'll be the same component except:

1) you insert another component for that entity
2) you delete the entity and create a new entity and modify its component

**Comment by Ploppz** [comment]
Ok thanks. Deletion of entities is bound to happen, so maybe this requires some extra bookkeeping, to assure integrity.

I have one additional remark: In my game there is a client and a server. They share the Component types. If I were to use `FlaggedStorage` on the server, the client will also have to use it. Unless I have different components for the client, which may or may not make sense - not sure yet. I don't currently see any other solution than how it is now though, specifying the storage as an associated type.

**Comment by torkleyy** [comment]
It's possible at runtime (`register_with`). You could use an enum to switch between storages.

At compile time doesn't work, you'd change the type (and the systems don't know what to fetch, the type id would change).

**Comment by Ploppz** [comment]
Thanks! That will do it.
