### ISSUE TITLE
Async/await support

### ISSUE THREAD

**Issue by sunjay** [slide-rs/specs#446]
Do you think it would be useful to support async functions and await in System implementations?

**Comment by torkleyy** [comment]
Hello @sunjay, as mentioned by @omni-viral, Specs is quite synchronous and async functionality is not a very good fit here. What would you want to use it for?

**Comment by sunjay** [comment]
The reason I brought it up is because, as I was working with specs, I started to wonder what would happen if I needed to load something asynchronously as part of the results of a system. The more I thought about it though, the more I realized that it doesn't really make sense to do that in the context of an ECS. Any async code should run separately as @omni-viral said.

I just wanted to bring this up to see what your thoughts were. I think it's worth talking about given that the language will have first class async support pretty soon. 

Thanks! This issue can probably be closed unless someone else has anything more to say. :smile:
