### ISSUE TITLE
Failure to call EntityBuilder::build() results in unexpected behaviour.

### ISSUE THREAD

**Issue by jojolepro** [slide-rs/specs#448]
Take the following code:
```
world.create_entity().with(MyComponent);
```

If you have a System running over MyComponent, it will see the entity and interact with it normally, but only for the first frame.
On the second frame, the entity will be gone.

It is really error prone and unexpected from the user's perspective.

**Comment by torkleyy** [comment]
There should be a warning.

**Comment by Xaeroxe** [comment]
Fixed in the next version of specs, this example will now generate a compiler warning

**Comment by Xaeroxe** [comment]
I'll look into it

**Comment by jojolepro** [comment]
Lost 2 hours on the network pr ;(

**Comment by Xaeroxe** [comment]
0.12.1 going up now, sorry @jojolepro

**Comment by Xaeroxe** [comment]
oh uh @torkleyy I lack permission to publish specs, can you add me as an owner?

**Comment by jojolepro** [comment]
:+1: thanks

**Comment by Xaeroxe** [comment]
Ok it's published now @jojolepro
