### ISSUE TITLE
Scene graph example

### ISSUE THREAD

**Issue by LaylConway** [slide-rs/specs#450]
A very common use case of an ECS is to create a scene graph that parents objects' transform to other objects. I'm however unsure how to implement this in specs. Could an example for this use case be added so it's a bit clearer how to do something like this? In general I would appreciate some pointers for implementing this.

**Comment by torkleyy** [comment]
Hello @LaylConway! I can link you to the implementation that the Amethyst game engine is using, just one sec.

**Comment by torkleyy** [comment]
So Amethyst is using `specs_hierarchy` to implement transform hierarchies, you can see the systems and components in this folder: https://github.com/amethyst/amethyst/blob/develop/amethyst_core/src/transform/components/parent.rs

**Comment by torkleyy** [comment]
A chapter would still be nice though.

**Comment by LaylConway** [comment]
Thanks for the quick answer! If you don't mind me asking, could you point me at the code where the transforms are actually resolved to a final model matrix for use in the renderer?

**Comment by torkleyy** [comment]
They don't get resolved by the renderer, but updated by the `TransformSystem` if necessary. There's a `GlobablTransform` component holding the matrix.

Some pointers:

* Here we check which nodes changed: https://github.com/amethyst/amethyst/blob/develop/amethyst_core/src/transform/systems.rs#L59

* Then we just iterate through all nodes (https://github.com/amethyst/amethyst/blob/develop/amethyst_core/src/transform/systems.rs#L94) and get the parent (which is stored as a component on an entity, so a `Parent` component on entity A containing entity B means A is a child of B) from the component storage (https://github.com/amethyst/amethyst/blob/develop/amethyst_core/src/transform/systems.rs#L96)

I don't know if you want to, but I recommend you just use [`specs-hierarchy`](https://github.com/rustgd/specs-hierarchy) for your project. It's our generic scene hierarchy library for Specs, you'll also find most of the hierarchy related code there.

**Comment by torkleyy** [comment]
Not sure if that actually answered your question?

**Comment by torkleyy** [comment]
@Aceeri wrote the code and @Rhuagh refactored it, so they probably know more about how it works than I do.

**Comment by LaylConway** [comment]
I think that probably answered my question yea, I'll take some time to look over these for my own implementation

**Comment by Rhuagh** [comment]
Depends on how complicated you want to make it, you can very easily make a system that recomputes all the world transforms every frame by using `specs-hierarchy`. You can just iterate through the entities with `hierarchy.all()`.

Something like:

```
for entity in hierarchy.all().into_iter() {
    let my_local = locals.get(entity);
    let my_parent = hierarchy.parent(entity);
    let parent_global = globals.get(entity);
   *globals.get_mut(entity) = parent_global * my_local;
}
```

**Comment by Rhuagh** [comment]
If you want to avoid recomputation when things aren't moving you should look at `TransformSystem` in amethyst. It's fairly involved, but that's because it wants to avoid recomputation.

**Comment by jrmiller82** [comment]
Would be nice to have a "how to use" specs-hierarchy example in either the docs or the slides.
