### ISSUE TITLE
specs-derive repo link on crates.io is wrong

### ISSUE THREAD

**Issue by icefoxen** [slide-rs/specs#453]
As the title says.

Also it's a little unclear how to use it from specs these days.  Do you use the separate crate?  Or is it hidden in `specs` itself somewhere?

**Comment by torkleyy** [comment]
Hello @icefoxen! Sorry for the late reply.

The `specs_derive` crate is in this repo, it's a top-level directory. You can use the crate by specifying it in your `Cargo.toml` like any other crate. Would you prefer to use a feature instead?

**Comment by torkleyy** [comment]
Thanks for reporting the wrong link, will be fixed.
