### ISSUE TITLE
Integrate with a collision detection algorithm

### ISSUE THREAD

**Issue by mattbettcher** [slide-rs/specs#456]
I noticed in the parallel benches example the collision system is marked as to do. I'm just wondering what the general ideas on how to integrate a spatially aware collision system would work with an ECS (specifically specs). 

My current idea is to use FlaggedStorage and subscribe to Modified events for Position Components (and possibly Velocity Components for swept collision detection) and basically update a completely separate and optimized structure to detect possible collisions. Mostly I'm just not sure how practical this is and how to get the list of possible collisions back to the correct entities for further processing. My assumption is to use a Resource and add lists of Targeted entities involved in each collision to it?

**Comment by Xaeroxe** [comment]
Pinging @Rhuagh who is our current expert on this subject

**Comment by minecrawler** [comment]
Are you looking for something like [collision-rs](https://github.com/Rhuagh/collision-rs)-based [rhusics](https://github.com/rustgd/rhusics), which is a collision detection library that can be used with specs?

You can see it's use at [amethyst-rhusics](https://github.com/amethyst/amethyst-rhusics), which integrates [rhusics](https://github.com/rustgd/rhusics) into the specs-based [Amethyst Game Engine](https://github.com/amethyst/amethyst)...

**Comment by mattbettcher** [comment]
Amazingly helpful! This is just exactly what I was looking for.
