### ISSUE TITLE
Join syntax seems unclear and relies too much on syntax magic

### ISSUE THREAD

**Issue by LaylConway** [slide-rs/specs#468]
This may just be primarily personal preference, but the join syntax gives of a very unclear and syntax-magic feeling to it. It's often unclear to me why exactly certain things have to be done and how they fit together. An example in code, from a helper function that takes storages by reference, to be called by a system:
```rust
for (entity, _, transform, matrix, ()) in (
    &**entities,
    &self.transform_modified,
    transforms,
    &mut *matrices,
    !&*parents,
).join()
```
Because of the syntax magic the `join()` function relies on, I have to do a lot of weird repeated referencing and de-referencing until I've got the type it wants. This makes no sense to me. As well, the use of the `!` operator, while concise, is very confusing when put next to de-referencing and referencing. If I were to personally pick an optimal syntax for this, regardless of practicality of implementation, I would go with something like this:
```rust
for (entity, _, transform, matrix, ()) in (
    entities.include(),
    self.transform_modified.include(),
    transforms.include(),
    matrices.include_mut(),
    parents.not(),
).join()
```
Something like this feels a lot more consistent to me. The code isn't littered as much with unclear repeated syntax magic punctuation. I feel an improvement like this is needed for specs code to be more easily readable and writable.

**Comment by WaDelma** [comment]
Firstly without context I cannot see why you would need to double on the dereferences here: `&*entities`, `&mut matrices` and `!&parents` should suffice.

Secondly you can already use `not` method from the `Not` trait if you prefer it.

Thirdly I agree that `&*entities` is unfortunate and maybe we should have method for that.

But I cannot see myself using `include` method proposed here as it would just make already verbose joins even more hard to read.

**Comment by LaylConway** [comment]
This is used in a function that takes all these types by reference, I'm splitting up a larger system like this to have more understandable individual parts. As a result of this, all de-referencing and referencing punctuation is necessary (except for `!&*parents` which I fixed just now). Even `&mut *matrices` is needed because rust otherwise assumes `matrices` has been moved when it's used again later in the function.

**Comment by Xaeroxe** [comment]
Unfortunately a style following "include" and "include_mut" isn't really possible as then every resource fetch in shred would have to assume mutation might occur, and that would basically bring specs back to a single threaded solution.

**Comment by torkleyy** [comment]
I think they meant that you'd only be able to use `include_mut` if you
actually did fetch it mutably, but still I don't see how that improves
anything. It just makes me type more which I'm trying to avoid.

**Comment by torkleyy** [comment]
> Even &mut *matrices is needed because rust otherwise assumes matrices has been moved when it's used again later in the function.

I don't understand, Rust uses automatic re-borrowing.

**Comment by Aceeri** [comment]
https://github.com/slide-rs/specs/pull/472

Partially fixes this, should no longer need some dereferencing.

**Comment by Aceeri** [comment]
@LaylConway What is the type of `matrices` by the way? Any component storage should be able to implicitly re-borrow I think?

**Comment by LaylConway** [comment]
The signature of the function this is used in is:
```rust
fn update_matrices<'a>(
        &mut self,
        entities: &Entities<'a>,
        hierarchy: &ReadExpect<'a, ParentHierarchy>,
        transforms: &ReadStorage<'a, TransformComponent>,
        parents: &ReadStorage<'a, ParentComponent>,
        matrices: &mut WriteStorage<'a, MatrixComponent>,
    )
```

**Comment by Aceeri** [comment]
@LaylConway Have you tried it without any reborrowing?

```
for (entity, _, transform, matrix, ()) in (
    entities,
    &self.transform_modified,
    transforms,
    matrices,
    !parents,
).join()
```

**Comment by Aceeri** [comment]
@LaylConway I just tried the example without reborrowing and it works:
```rust
fn take_storages(
    entities: &Entities,
    positions: &mut WriteStorage<Pos>,
    velocities: &ReadStorage<Vel>,
) {
    for (entity, pos, vel) in (entities, positions, velocities).join() {
        pos.0 += vel.0;
    }
}

impl<'a> System<'a> for SysA {
    type SystemData = (Entities<'a>, WriteStorage<'a, Pos>, ReadStorage<'a, Vel>);
    fn run(&mut self, (entities, mut pos, vel): Self::SystemData) {
        take_storages(&entities, &mut pos, &vel);
    }
}
```

**Comment by LaylConway** [comment]
@Aceeri You'll get the issue if you use positions later again in that function.

**Comment by Aceeri** [comment]
Ah, I see now. Weird.... I would've thought Rust would know to re-borrow here.

**Comment by torkleyy** [comment]
nah, moving to the tuple

**Comment by Aceeri** [comment]
@LaylConway In the least we only need to re-borrow mutable references like so:
```
for (entity, _, transform, matrix, ()) in (
    entities,
    &self.transform_modified,
    transforms,
    &mut *matrices,
    !parents,
).join()
```

**Comment by torkleyy** [comment]
I understand that things might seem unclear at first but I don't really see us changing the joining, so I'll close this issue.
