### ISSUE TITLE
ReadExpect docs claim that ReadExpect allows mutable fetching.

### ISSUE THREAD

**Issue by DefecateRainbows** [slide-rs/specs#471]
Was this the intended behavior? I was under the impression that read fetched immutably.

**Comment by DefecateRainbows** [comment]
Relevant source: https://docs.rs/shred/0.7.0/src/shred/res/data.rs.html#170
Relevant doc pages: https://docs.rs/specs/0.12.2/specs/type.ReadExpect.html

**Comment by torkleyy** [comment]
You're right, that's a copy&paste mistake.

**Comment by torkleyy** [comment]
Thank you for creating the issue, a PR to fix this will be merged soon.
