### ISSUE TITLE
Document behaviour of `.insert()` and `.with()` when component already exists

### ISSUE THREAD

**Issue by zesterer** [slide-rs/specs#475]
Currently, the docs specify the following:

![image](https://user-images.githubusercontent.com/3268430/45760850-edd6fe00-bc22-11e8-9329-3f191dfb4143.png)

It would be nice to know what the behaviour of the following is, or at least whether the behaviour is undefined or not.

```rs
world.create_entity()
    .with(Pos(0, 0))
    .with(Pos(1, 1))
    .build();
```

**Comment by Aceeri** [comment]
Consecutive `with` and `insert` overwrite the previous component: https://github.com/slide-rs/specs/blob/master/src/storage/mod.rs#L404 

Would agree it might be nice to have defined documentation for that, but I think it is pretty standard to overwrite.
