### ISSUE TITLE
marry specs with glium

### ISSUE THREAD

**Issue by pum-purum-pum-pum** [slide-rs/specs#480]
I'm trying to use specs with glium. However glium stuff couldn't be stored in specs components/resources because it's single threaded. So I ended up with pushing all glium stuff in System fields(which I believe I can call without any multi-threading). However when I call something like 
```   
rendering_system.run_now(&ecs_world.res);
// stateless_rendering_system.run_now(&ecs_world.res);
ecs_world.maintain();
```
compiler says:
```
 rendering_system.run_now(&ecs_world.res);
    |                               ------------- immutable borrow occurs here
187 |     // stateless_rendering_system.run_now(&ecs_world.res);
188 |     ecs_world.maintain();
    |     ^^^^^^^^^ mutable borrow occurs here
...
389 | }
    | - immutable borrow ends here
```
And with stateless renderer
```   
// rendering_system.run_now(&ecs_world.res);
stateless_rendering_system.run_now(&ecs_world.res);
ecs_world.maintain();
```
everything works fine.

How can I ensure the compiler that i'm not saving reference to the world inside my rendering system. Or may be there is the way to use glium with specs that I did not realize?

(m.b. it's something obvious here. I'm new to Rust :) )

**Comment by omni-viral** [comment]
It seems that you have borrowing problem that is not specific to specs at all. Please provide exact code snipped of the function you try to compile.

**Comment by pum-purum-pum-pum** [comment]
While trying to distill my code to snippet found a bug with lifetimes...
Just changed:
```
impl<'a> System<'a> for Renderer<'a> 
```
to
```
impl<'a, 'b> System<'a> for Renderer<'b> 
```
everything works fine. Thank You.

**Comment by pum-purum-pum-pum** [comment]
I have  &'a glium::Display in my Renderer. And SystemData have the same lifetime 'a. So I guess I forced SystemData to live as long as display lives?

**Comment by omni-viral** [comment]
Yeap. That's why `Dispatcher` requires `for<'a> System<'a>` implementation for systems. E.g. implemented for lifetime, not particular one.
BTW. Why don't you use `Dispatcher`?

**Comment by pum-purum-pum-pum** [comment]
Yes I rewrote it with dispatcher with `with_thread_local`. This could be closed I guess.
