### ISSUE TITLE
DenseVecStorage is not really that dense - should be mentioned in the docs?

### ISSUE THREAD

**Issue by idanarye** [slide-rs/specs#484]
Reading [the `DenseVecStorage` docs](https://slide-rs.github.io/specs-website/docs/docs/0.10/specs/struct.DenseVecStorage.html) gives the impression that everything is densely packed, trading some access performance for better memory usage. Which is true - but a bit misleading, since only the data is dense. The index vector is still sparse.

I think it's worth mentioning that in the docs - that `DenseVecStorage` can still have a big memory footprint for a small number of entities if their IDs are large.

**Comment by torkleyy** [comment]
Fair point.

**Comment by zeroexcuses** [comment]
Thanks for pointing this out. Up until this point, I thought "DenseVecStorage" was

"entity id -> location" in BTree,
"location -> data" in Vec

Was not aware the "entity -> location" was in a sparse Vec
