### ISSUE TITLE
Saveload example that features serializing/deserializing a whole `World`

### ISSUE THREAD

**Issue by expenses** [slide-rs/specs#497]
Now that #460 has been merged, do you think we can get a more updated saveload example? I havent had much of a look at the existing docs, but it seems a little confusing. How would I go about e.g. serializing a whole `World`?

**Comment by expenses** [comment]
Actually, the docs for the `specs::saveload::ConvertSaveload` for the git version are pretty decent, what I'm really after is an easy example for serializing _everything_ contained in a `World`.

**Comment by torkleyy** [comment]
You cannot just serialize the whole world, you would have to specify the components individually.

**Comment by expenses** [comment]
Oh ok, would there be a way to implement that? It would be incredibly helpful.

**Comment by torkleyy** [comment]
This is basically blocked by Rust, we need specialization for implementing that feature.

**Comment by torkleyy** [comment]
There is `AnyStorage` which we have a collection of, but not every component is serializable. If there was specialization, it could provide a method that serializes the components if possible.

By specifying all the types we can statically retrieve the implementation for `Serialize` / `Deserialize`.

**Comment by expenses** [comment]
Got it, thanks. I'll try my hand at serializing the individual components, I just have quite a few of them haha

**Comment by Riey** [comment]
@torkleyy 

I want to saveload World either

`specialization` feature is not stable yet but it's possible to apply to Serialize and Deserialize

I make crate for that https://crates.io/crates/maybe-serde

it can be help for solve this issue?

**Comment by torkleyy** [comment]
Interesting! I think it could be used for this, yes.
