### ISSUE TITLE
Cargo doc not showing all modules?

### ISSUE THREAD

**Issue by jrmiller82** [slide-rs/specs#502]
I apologize in advance if this a noob question, but I like to drowse the documentation locally, so I routinely run `cargo doc --all --open`. I don't see the `saveload` module in 0.12.3 nor if I run from master via github. Is there a crate option I'm supposed to set or something like that? https://docs.rs/specs/0.12.3/specs/ shows what I expect to see. 

Thanks in advance.

**Comment by WaDelma** [comment]
You need to do: `cargo doc --all --open --features "serde"` to enable saveload

**Comment by jrmiller82** [comment]
Thank you! Trying it out now.
