### ISSUE TITLE
Use something other than `from` and `into` for `ConvertSaveload`

### ISSUE THREAD

**Issue by expenses** [slide-rs/specs#503]
`from` and `into` conflict with `std::convert::From` and `std::convert::into`, which are implemented a lot, meaning that using `ConvertSaveload` requires a lot of type annotations.

**Comment by torkleyy** [comment]
Okay, makes sense. Do you have a better suggestion?

**Comment by expenses** [comment]
`convert_into`, `convert_from` perhaps?

**Comment by torkleyy** [comment]
Hmm, okay. That works for me.

**Comment by torkleyy** [comment]
@expenses Your PR is part of Specs version `0.14`.
