### ISSUE TITLE
Feature Request: API for adding component to existing entity

### ISSUE THREAD

**Issue by jrmiller82** [slide-rs/specs#510]
For one offs (world gen type functions), I'm having trouble thinking procedurally. 

Say, I have a space ship, with 2 mandatory components and 2 optional components. 

if I do 

```
let e = world.create_entity().with(Mandatory1 {...}).with(Mandatory2{...}).build();

// it'd be real nice to be able to then do something like this:
if Optional1 == true {
e.insert(Optional1 {...})
}
// OR it'd be really nice to do something like this,
world.add_component_to_existing_entity(e, Optional1{...}}) 
// OR
world.add_component_to_existing_entity(&e.id, Optional1{...})
// if that helps get around a circular borrow.
}
```
Thoughts?

Right now, I can't see how to do this other than to write three separate world.create_entity lines, one without either option, one with only Option1, and one with only Option2. That's super clunky and has a  ton of code repetition. In my real game, there are like 8 optional components, so doing that by hand is going to get old quickly. 

I could also manually set up the world.WriteStorage calls to use that syntax as shown in the slides, but then you get into borrowing issues with the world. 

Even if the call is slow, I think there needs to be some sort of simpler way to CRUD components on an entity, likely through a simple call to a mutable ref world struct.

**Comment by adeschamps** [comment]
You can store the returned builder from the `create_entity` method, and modify it later:

```rust
let mut builder = world.create_entity().with(Mandatory1 {...}).with(Mandatory2 {...});
if optional_1 {
    builder = builder.with(Optional1 {...});
}
if optional_2 {
    builder = builder.with(Optional2 {...});
}
let e = builder.build();
```

**Comment by jrmiller82** [comment]
Came here to post this i.e. I figured it out.

```
/// is used to pass as an argument to `new_ship()`
pub struct ShipConstructor {
    pub name: String,
    pub hull: Hull,
    pub engine: Engine,
    pub sensors: Sensor,
    pub armor: Option<Armor>,
    pub shields: Option<Shields>,
    pub weapons: Option<Weapons>,
    pub cargo: Cargo,
}

pub fn new_ship(s: ShipConstructor, w: &mut World) -> Result<(), Error> {
    let mut eb = w
        .create_entity()
        .with(Ship { name: s.name })
        .with(s.hull)
        .with(s.engine)
        .with(s.sensors)
        .with(s.cargo);

    if let Some(i) = s.armor {
        eb = eb.with(i.clone());
    }
    if let Some(i) = s.shields {
        eb = eb.with(i.clone());
    }

    if let Some(i) = s.weapons {
        eb = eb.with(i.clone());
    }

    eb.build();

    Ok(())
}
```

Maybe something like this should be added to the docs?

**Comment by jrmiller82** [comment]
Thanks @adeschamps ; looks like I figured out something similar. I might submit a PR for fixing the EntityBuilder documentation.

**Comment by jrmiller82** [comment]
PR #511 added. Please feel free to tweak; I just think showing that workflow will save multiple people new to the repo a chunk of time.

**Comment by jrmiller82** [comment]
@torkleyy You're welcome. :)

**Comment by omni-viral** [comment]
@jrmiller82 
>
```
// OR it'd be really nice to do something like this,
world.add_component_to_existing_entity(e, Optional1{...}})
```

`world.write_component::<Optional1>().insert(e, Optional1{...});`

**Comment by jrmiller82** [comment]
@omni-viral Thanks.
