### ISSUE TITLE
Lifetime issues with component storages

### ISSUE THREAD

**Issue by sunjay** [slide-rs/specs#519]
I originally posted about this in [the users forum](https://users.rust-lang.org/t/returning-iterator-of-specs-components/23012?u=sunjay) and then on [Reddit](https://www.reddit.com/r/rust/comments/a45q5i/a_simple_agenda_for_the_rust_game_development_wg/ebkdwjq/?context=1).

*Terminology Note:* When I say "owned X" in the text below, I mean that you have ownership of a value X of type `T`, not a reference to that value (e.g. `&T` or `&mut T`)

You can look at this issue from two perspectives:

1. It is hard to get a `SystemData` containing references to storages.
    Example: You can get `(ReadStorage<A>, ReadStorage<B>)` by calling the `system_data` method on `World` but not `(&ReadStorage<A>, &ReadStorage<B>)`
2. It is not possible to use the `Join` trait with the owned versions of component storages.
    Example: You can do `(&a, &b).join()` but not `(a, b).join()`

Both of these issues exist for good reasons, but they make code like the following very hard to write:

```rust
fn iter_components<'a>(world: &'a World) -> impl Iterator<Item=(&Position, &Velocity)> + 'a {
    // Two *owned* storages allocated on the stack of this function
    let (positions, velocities) = world.system_data::<(ReadStorage<Position>, ReadStorage<Velocity>)>();

    // Returning a reference to stack allocated data (does not and should not work!)
    (&positions, &velocities).join()
}
```

This doesn't work and you get the following error: (copied from users forum post, see that for the full code example)

```
error[E0515]: cannot return value referencing local variable `velocities`       
  --> src/main.rs:22:5                                                          
   |                                                                            
22 |     (&positions, &velocities).join()                                       
   |     ^^^^^^^^^^^^^-----------^^^^^^^^                                       
   |     |            |                                                         
   |     |            `velocities` is borrowed here                             
   |     returns a value referencing data owned by the current function         
                                                                                
error[E0515]: cannot return value referencing local variable `positions`        
  --> src/main.rs:22:5                                                          
   |                                                                            
22 |     (&positions, &velocities).join()                                       
   |     ^----------^^^^^^^^^^^^^^^^^^^^^                                       
   |     ||                                                                     
   |     |`positions` is borrowed here                                          
   |     returns a value referencing data owned by the current function
```

If either of the two things I listed above weren't the case, this code could potentially compile:

1. If you could get a system data instance containing references to storages: (the storages would have to be owned within the world or something)

```rust
fn iter_components<'a>(world: &'a World) -> impl Iterator<Item=(&Position, &Velocity)> + 'a {
    // Two references to storages allocated somewhere by World
    // Notice the `&` before the `ReadStorage` types here
    let (positions, velocities) = world.system_data::<(&ReadStorage<Position>, &ReadStorage<Velocity>)>();

    // positions and velocities are both references, so we can use them here no problem
    (positions, velocities).join()
}
```

2. If it were possible to use the `Join` trait on owned versions of the storages:

```rust
fn iter_components<'a>(world: &'a World) -> impl Iterator<Item=(&Position, &Velocity)> + 'a {
    // Two *owned* storages allocated on the stack of this function
    let (positions, velocities) = world.system_data::<(ReadStorage<Position>, ReadStorage<Velocity>)>();

    // Storages are *moved* into this tuple that we call `join` on. This works!
    (positions, velocities).join()
}
```

A note about this: `ReadStorage` makes it pretty obvious that we are immutably borrowing here, but with `WriteStorage` we would probably need some methods like `read_owned()` and `write_owned()` to emulate what you could do with `&` and `&mut` before. See the following code for more details:

```rust
fn iter_components<'a>(world: &'a World) -> impl Iterator<Item=(&mut Position, &Velocity)> + 'a {
    // Two *owned* storages allocated on the stack of this function
    let (positions, velocities) = world.system_data::<(WriteStorage<Position>, WriteStorage<Velocity>)>();

    // You can join over either of these storages in two modes:
    // * `&positions` for read-only access to the components
    // * `&mut positions` for read-write access to the components
    // `write_owned()` could wrap the storage in a type that implements
    // the `Join` trait and allows access to mutable references
    // Instead of `read_owned()` we could default to the behaviour that
    // the owned version of a storage only allows reading

    // Storages are *moved* into this tuple that we call `join` on. This works!
    (positions.write_owned(), velocities.read_owned()).join()
}
```

I think this solution is probably the easiest to implement because it doesn't involve the `World` having to hold on to arbitrary storages for some extended amount of time.

The API I would suggest is:

* `ReadStorage<T>` and `WriteStorage<T>` implement `Join` and produce `&T`
* `WriteStorage<T>` provides a method (e.g. `write_owned()`) that returns an owned value that implements `Join` and produces `&mut T` (perhaps something similar to `MaybeJoin`?)

This may cause issues with `World` because it's probably not a good thing if a storage lives longer than expected. I am not familiar enough with the internals to comment on that.

**Comment by Xaeroxe** [comment]
Option 1 is much more serviceable in my opinion.  `Join::join` takes `self` as a parameter, consuming it, which is very likely to cause confusion for users who might start operating under the mistaken belief they can't use `join` twice on a storage.

**Comment by sunjay** [comment]
> Option 1 is much more serviceable

I'm happy with either. I don't actually know the internals well so my suggestion was just a guess :)

**Comment by torkleyy** [comment]
Thanks for filing this @sunjay!

I don't see a good way to implement Option 1. These values need to be held in memory because they protect memory from being accessed in an invalid manner.

What you can do though:

```rust
struct Iter<'a> {
    pos: WriteStorage<'a, Position>,
    vel: ReadStorage<'a, Velocity>,
}

impl<'a> Iter<'a> {
    fn iter(&mut self) -> impl Iterator<Item = (&mut Position, &Velocity)> + 'a {
        (&mut self.pos, &self.vel).join()
    }
}

fn iter_components<'a>(world: &'a World) -> Iter<'a> {
    let (pos, vel) = world.system_data::<(WriteStorage<Position>, WriteStorage<Velocity>)>();

    Iter {
        pos, vel,
    }
}

// Then:

iter_components(&world).iter().do_whatever();
```

This works because Rust will just keep the value in memory for as long as necessary and drop it once it's not borrowed anymore (so basically create the temporary for you).

As for the second option, that could be implemented, yes. I share @Xaeroxe's concern though.

I don't quite know what you're trying to achieve, but what I do usually is:

```rust
world.exec(|(vel: ReadStorage<Velocity>, pos: WriteStorage<Position>)| {
    (&vel, &mut pos)
        .join()
        .do_something()
});
```

If you want to hide the world and you plan on creating more of those convenience functions, one thing you can do is create `RefJoin` and `MutJoin` which wrap a `T` where `&T` / `&mut T` is `Join` and implement `Join` with that constraint. That would allow you to return `(MutJoin(pos), RefJoin(vel)).join()`.

**Comment by sunjay** [comment]
> I don't quite know what you're trying to achieve

I have a bunch of components that I want to move from one `World` to another. I want to do this several times in different places, so I want one function/struct/something that deals with iterating through all the components. It's hard to do that starting from a world without first defining a system data for all the components.

> If you want to hide the world and you plan on creating more of those convenience functions, one thing you can do is create RefJoin and MutJoin which wrap a T where &T / &mut T is Join and implement Join with that constraint. That would allow you to return (MutJoin(pos), RefJoin(vel)).join().

Could something like `MutJoin` or `RefJoin` be added to specs?

**Comment by torkleyy** [comment]
Ah, I see.

> Could something like MutJoin or RefJoin be added to specs?

I'm not against it, but it's kind of a special case. I'd like to hear @Xaeroxe's and @WaDelma's opinion prior to merging it.

**Comment by torkleyy** [comment]
Let's revisit this after #523

**Comment by torkleyy** [comment]
We could also implement `Join` directly for the storages, making `Storage<FetchMut>` simply always mutable. I don't think that would be bad considering we consume it anyway. That way, this can be solved much more consistently.

## Task

* create to impl blocks of `Join` for `Storage`
* look at how `Storage` abstracts over the mutability of `D`
* implement one for the mutable and one for the immutable version

**Comment by torkleyy** [comment]
It turns out this is actually not as easy as I thought. The proposed solution does not work since we obviously can't borrow fields we're consuming.

**Comment by m4b** [comment]
If I understand this issue right, I've been meaning to file something similar. I basically want something similar:

```rust
fn iter_components<'a, T>(world: &'a World) -> impl Iterator<Item=&'a T> + 'a
```

The reason I want this is I want to treat the world as a black box, i start it, things happen, and then someone else can query what happened to a list of things inside, and iterate through them, and update some other data they might have that relates, etc.

If I attempt to write this function, I have lifetime errors; this just seems like a bug to me though, or the lifetimes aren't threaded correctly; not sure.

Otherwise, I'm forced to clone, or i'm forced to execute in the context of the world, which would require someone else to know that I'm using specs as the black box, which means the backend is leaking out imho.

**Comment by torkleyy** [comment]
There's nothing incorrect about the lifetimes, it's inherited by interior mutability. The same happens when you try to return a refefence to a value inside a `Mutex`. You need to keep the guard in memory so access can be controlled.

I do understand your concern though.

**Comment by sunjay** [comment]
Any idea if there is something we can do about this? Maybe there could be another different type that gets returned from a different method that specially supports this?

**Comment by torkleyy** [comment]
There is no way to directly return multiple immutable references to resources.

What we can do, however, is returning a `Ref<MyResource>` which dereferences to the resource. Is that something that would work for you?

**Comment by sunjay** [comment]
I think that's a reasonable compromise. Does that require a new method / struct? Or can it be integrated into the existing API?

**Comment by torkleyy** [comment]
I think it does work right now :)

[`Resources::fetch`](https://docs.rs/shred/0.7.0/shred/struct.Resources.html#method.fetch) fetches the resource and gives you a `Fetch<MyResource>` (not `Ref`, confused that)

**Comment by sunjay** [comment]
Is there anything more we want to do with this?

**Comment by torkleyy** [comment]
I'm not quite sure. I think `Ref` can be used just fine for this use case, and other than that I'm not sure what to solve here. Do you think there's still something left to do?

**Comment by sunjay** [comment]
I just wanted to check to be sure. Thanks for your help! :smile:
