### ISSUE TITLE
Useful resource: Gluon bindings

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#520]
@Marwes wrote a nice module that allows using Specs with Gluon. I haven't checked it in detail yet, but maybe it's helpful to somebody.

https://github.com/Marwes/shred-example/blob/master/src/gluon_system.rs

**Comment by Marwes** [comment]
Linking this comment as well https://github.com/amethyst/amethyst/issues/271#issuecomment-416617254

> Despite the fact that it is extremely rough and has some hilariously unsafe code I think I should still bring up the specs/shred-gluon integration I have been sketching out. Still, it does sort of work and I haven't found any unsolvable blockers yet.
>
> The main issue is that the support for dynamic systems in specs/shred is rather lackluster at the moment, part of it can be solved by exposing a few currently private function with regard to component extraction (which shouldn't affect the safety in any way). There might very well be possible to provide a better dynamic system abstraction in the crates themselves which could be another way of fixing it.
>
> On the gluon side the main issue is that I have to cast away the lifetimes to pass in borrowed resources to the virtual machine. I think gluon can be improved to support that however.
>
> https://github.com/Marwes/shred-example/blob/master/src/gluon_system.rs
https://github.com/Marwes/shred-example/blob/master/src/gluon_system.glu

And I'd like to emphasize again that it is very much a "get shit working project", it uses plenty of unsafe to get around lifetime errors which need to get removed or at the very least packaged under a safe interface.

Still, it does at least show the possibility of something nice!

**Comment by torkleyy** [comment]
Cleaning up the issue tracker, I'll close this.

I've created awesome-specs for these cases; see https://github.com/slide-rs/awesome-specs/pull/1
