### ISSUE TITLE
serde-derive  in crates.io impl an older version of ConvertSaveload

### ISSUE THREAD

**Issue by lassade** [slide-rs/specs#521]
serde-derive from crates.io still using a old impl for ConvertSaveload when it was using the `into` and `from` methos instead of `convert_from` and `convert_into`; Maybe a version bump will sove the issue?

**Comment by torkleyy** [comment]
@lassade I'm a little confused what you mean here. `serde-derive` is not a crate we publish, and it's stable so there should be no version conflicts.

**Comment by torkleyy** [comment]
Ah, I see what you mean now. `specs-derive` does not provide the correct impl for the latest version.
