### ISSUE TITLE
Make `World` an extension of `Resources`

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#523]
`World` is basically an extension of `Resources`. I feel this makes the API a bit inconsistent because

1) you cannot use the `World` API if you have just `Resources`
2) you have both the `World` and the `Resources` API to deal with

### Trait

Make `World` a trait that is implemented for `Resources`. The `new` function can be implemented

1) using a free function (`new_world() -> Resources`)
2) doing a `impl World { pub fn new() -> Resources }`

### Free standing functions

Provide functions like

* `ǹew_world`
* `read_component<T>(&Resources)`
* etc

**Comment by torkleyy** [comment]
This would be a breaking change unfortunately, although we can limit its impact if we choose the former.

**Comment by azriel91** [comment]
I'd vote for the extension trait, also today I learned that you can have an inherent method implemented on a trait type.

**Comment by jojolepro** [comment]
trait over resources

impl World for Resources

**Comment by KuSpa** [comment]
Just using a Trait without reducing either API, Resources would have `fetch` as well as `read_storage`, which is exactly the same. 
To not to confuse the user, I would remove the wrapping methods or rename Resources' methods. Doing either would heavily impact everyone, who's using the other API.

**Comment by TimonPost** [comment]
Concrete steps to clarify this issue.

1. [ ] Rename `shred::Resources` to `shred::World`
2. [ ] Remove methods from `specs::World` into `specs::WorldExt`
	- read_storage / write_storage should be removed completely.

**Comment by torkleyy** [comment]
This is still relevant.

**Comment by torkleyy** [comment]
Fixes by #550
