### ISSUE TITLE
Does Nitric mean that specs should have a 1.0 release?

### ISSUE THREAD

**Issue by icefoxen** [slide-rs/specs#524]
Exactly what the title says.  If there's a successor to specs in the works, can we consider specs stable?

**Comment by torkleyy** [comment]
Yes, in fact I'm planning to release a 1.0 in the next weeks.

**Comment by torkleyy** [comment]
The only major change required for thaz is #523

**Comment by torkleyy** [comment]
Tracking progress in https://github.com/slide-rs/specs/issues/532
