### ISSUE TITLE
Scoped parallel execution within a single System

### ISSUE THREAD

**Issue by kvark** [slide-rs/specs#54]
@Kimundi:

> Would it be possible to support scoped-parallel iteration over entities in a System? As in, having a build-in way to distribute work over the backing threadpool of specs rather than "working around" that with multiple systems and/or launching your own threadpool

Suggestions: use `crossbeam` or `rayon`
A nice library for our consideration - https://github.com/reem/rust-shared-mutex

**Comment by WaDelma** [comment]
I'll try to switch threadpool for rayon. (Wanted to test speed difference and stumbled into #116)

**Comment by WaDelma** [comment]
I have been looking at how to integrate `rayon` to `specs`.
I currently have just switched thread pool to use `rayon` one which seemed to need `rayon-core` which is currently unstable, but switching it was easy enough.

Bigger task is to implement parallel iterator for the `join` stuff as it required touching the `bitset`.
Is there any sources that explain it other than the code? Only thing that I found searching 'Hierarchical bitset' was [this](http://www.cs.loyola.edu/~binkley/papers/tcsrt08-hbit-vectors.pdf) pdf. It seems at cursory clance to be similar. Is it accurate?

I am also currently little lost in `rayons` internals even though I have pretty much watched all the video presentations and read blogs on it. Have to just put time in to familiarise myself with the code base.

**Comment by WaDelma** [comment]
Also crossbeam is currently in flux:
https://www.reddit.com/r/rust/comments/5ygbwb/crossbeam_request_for_help/
https://www.reddit.com/r/rust/comments/5yp2b2/initial_release_candidate_100_by_ticki_pull/

**Comment by torkleyy** [comment]
Implemented by PR #120 by @WaDelma.
