### ISSUE TITLE
Audit all uses of `unsafe`

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#548]
* [ ] Collect all `unsafe` expressions
* [ ] Make sure they all have a comment with the respective reasoning
* [ ] Publish the results & merge missing reasoning into the respective repos

The following crates should be included:

* `specs`
* `shred`
* `hibitset`

**Comment by torkleyy** [comment]
cc @fletcher Any more suggestions here?

**Comment by fletcher** [comment]
Not sure you meant to cc me on it?  Perhaps someone else?

**Comment by torkleyy** [comment]
Yeah, sorry.

**Comment by torkleyy** [comment]
cc @fhaynes

**Comment by torkleyy** [comment]
Working on this now.

**Comment by torkleyy** [comment]
I've covered most of it in #566, but some points remain.
