### ISSUE TITLE
Unable to mutate WriteStorage when SystemData is a struct

### ISSUE THREAD

**Issue by tuzz** [slide-rs/specs#558]
## Description

Hello, [in the docs it says you can create a struct to hold your `SystemData`](https://slide-rs.github.io/specs/06_system_data.html#specifying-systemdata). I've tried this, but I don't know how to get mutable access to a field of type `WriteStorage`. Is this possible?

Here's a minimal example that demonstrates the problem:

**main.rs**

```rust
use specs::prelude::*;

#[macro_use] extern crate shred_derive;
#[macro_use] extern crate specs_derive;

#[derive(Component)] pub struct Foo;
#[derive(Component)] pub struct Bar;

#[derive(SystemData)]
pub struct MyData<'a> {
    foos: ReadStorage<'a, Foo>,
    bars: WriteStorage<'a, Bar>,
}

struct MySystem;

impl<'a> System<'a> for MySystem {
    type SystemData = MyData<'a>;

    fn run(&mut self, data: Self::SystemData) {
        for (_, _) in (&data.foos, &mut data.bars).join() { }
    }
}

fn main() { }
```

**Cargo.toml**

```
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

[dependencies]
specs = "*"
specs-derive = "*"
shred = "*"
shred-derive = "*"
```

**cargo run (output)**

```
error[E0596]: cannot borrow `data.bars` as mutable, as `data` is not declared as mutable
  --> src/main.rs:21:36
   |
20 |     fn run(&mut self, data: Self::SystemData) {
   |                       ---- help: consider changing this to be mutable: `mut data`
21 |         for (_, _) in (&data.foos, &mut data.bars).join() { }
   |                                    ^^^^^^^^^^^^^^ cannot borrow as mutable
```

I'm not sure if this is a bug or not. Is there some way to get mutable access to the `WriteStorage` ?

Thanks

**Comment by adeschamps** [comment]
The issue isn't with the storage - the variable `data` itself needs to be mutable. Make the change that the computer error suggested, and you should be fine.

**Comment by tuzz** [comment]
Ahh, thanks. I don't know how I missed that! 👍
