### ISSUE TITLE
Contact cuviper at the Rayon project to see what the status is of parallelism in WASM.

### ISSUE THREAD

**Issue by fhaynes** [slide-rs/specs#580]
The WASM WG said they have made a great deal of progress on it. We need to figure out exactly how much, and how we can experiment with it. Is it on a branch somewhere? A fork?

fitzgen on the Rust Discord might know as well, or alexcrichton

**Comment by jojolepro** [comment]
Contacted on discord

**Comment by jojolepro** [comment]
![image](https://user-images.githubusercontent.com/4755185/57092322-2d95b600-6cd9-11e9-8f45-f8c9c72e45c8.png)

**Comment by torkleyy** [comment]
https://github.com/rayon-rs/rayon/pull/636#issuecomment-499261214 :tada:

**Comment by jojolepro** [comment]
yaaaaaaay
