### ISSUE TITLE
Review prior art

### ISSUE THREAD

**Issue by fhaynes** [slide-rs/specs#581]
Review https://rustwasm.github.io/2018/10/24/multithreading-rust-and-wasm.html to get an idea of where we are starting from.

**Comment by torkleyy** [comment]
@jojolepro Anything left to do here?

**Comment by jojolepro** [comment]
wait for this to get merged https://github.com/rayon-rs/rayon/pull/636

**Comment by erlend-sh** [comment]
It’s been merged.

**Comment by jojolepro** [comment]
I made an example of specs running on wasm here https://github.com/jojolepro/specs_wasm
