### ISSUE TITLE
Add UUID mappings

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#582]
## Description

Add a UUID component and a UUID allocator.

The component provides the `Entity -> UUID` mapping, the allocator maps `UUID -> Entity`.

It should be possible to re-use the `saveload` module for this, by implementing `Marker` and `MarkerAllocator` for `UuidComponent` and `UuidAllocator`, respectively.

Please add tests and an example.

## Motivation

This allows unique identification of entities beyond one running `World`, e.g. sharing entities over the network.

---

cc @jojolepro

**Comment by ldesgoui** [comment]
#584 was merged but this issue wasn't closed, is anything more needed?

**Comment by torkleyy** [comment]
Yes, I think we don't have an example yet.

**Comment by torkleyy** [comment]
Actually, `saveload` should be enough for now.
