### ISSUE TITLE
Allow is_alive() to be called from the Entities struct

### ISSUE THREAD

**Issue by johann2** [slide-rs/specs#59]
It would be much more ergonomic and you wouldn't need to get read lock for the whole world just for that. Most usage of is_alive() is in systems and right now the only place where you could call it there is inside arg.fetch. As far as I understand, running whole systems inside fetch would stop any parallel processing from happening.

I'd suggest the same thing for  create_later() and delete_later() but I don't understand how they work yet.

**Comment by kvark** [comment]
why do you even need to call `is_alive()`?

**Comment by johann2** [comment]
Ah I understand now. For some reason I didn't realize that deleting an entity would also delete its components, meaning that it's enough to just check if an entity still has a required component.

**Comment by kvark** [comment]
yeah, I suppose we can close this then
