### ISSUE TITLE
Turn U64Marker/U64MarkerAllocator into generics over a "marker" trait

### ISSUE THREAD

**Issue by ldesgoui** [slide-rs/specs#592]
## Description

`U64Marker` becomes `U64Marker<T: ?Sized>`, `U64MarkerAllocator` turns into `U64MarkerAllocator<T: ?Sized>`, allowing the following:

```rust
struct Networked;
struct FileSaved;

fn setup(world: &mut World) {
    world.register::<U64Marker<Networked>>;
    world.register::<U64Marker<FileSaved>>;
    world.add_resource(U64MarkerAllocator::<Networked>::default());
    world.add_resource(U64MarkerAllocator::<FileSaved>::default());
}
```

## Motivation

The provided implementation for Marker is most likely good enough for a large majority of the use-cases, however the inability to use it more than once is limiting.

## Drawbacks

* Is it a breaking change?

It is a breaking change

* Can it impact performance, learnability, etc?

Arguably, the added set of carets for the generic type makes the code busier.
ZST, etc might not be the friendliest to newcomers.
I don't see how performance could be impacted.

## Unresolved questions

I'm not the most knowledgeable in terms of generics, isn't it possible to have "default" generics? If so, the changes would only be additive and not breaking.
If it comes down to breaking changes, a rename should be considered, I feel that `SimpleMarker` could be more appropriate.

---

I should be able to spend time on a PR implementing this if accepted

**Comment by torkleyy** [comment]
I like the change, but I would be cautios about default parameters. If you forget the perameter, you can easily access the wrong marker accidentally.
