### ISSUE TITLE
EntitiesRes::delete() runs before LazyUpdate::exec_mut()

### ISSUE THREAD

**Issue by JMS55** [slide-rs/specs#600]
## Description

Since both functions are atomic, I expect them to run in the order I call them. delete() seems to always run before exec_mut(), however, which causes issues since the entity is no longer alive when exec_mut() is called.

Doing ` lazy_update.exec(move |world| world.entities().delete(entity).unwrap());` instead of delete() works however

## Meta

Rust version: `1.35.0 (3c235d560 2019-05-20)`
Specs version / commit: `0.14.3`
Operating system: `Windows 10`

## Reproduction

1. Call LazyUpdate::exec_mut() and try to get a component of entity X within
2. Call EntitiesRes::delete(X)
3. Crashes in exec_mut(), as entity X is no longer alive

## Expected behavior

Entity X would still be alive

**Comment by WaDelma** [comment]
This is not a bug: `exec_mut` is run lazily and `delete` is atomic.
When `delete` gets called it's instantly destroyed. The components associated with this entity will be then lazily deleted in `maintain`.
Everything `LazyUpdate` does it does lazily on `maintain`. All `LazyUpdate` stuff is done after doing the component deletion, which is not documented (?), but the other way around would be odd as the entity doesn't exists anymore.

**Comment by JMS55** [comment]
Ahh thanks for clearing that up
