### ISSUE TITLE
Code examples lack definitions of some variables, making it hard to read.

### ISSUE THREAD

**Issue by yuvallanger** [slide-rs/specs#602]
## Description

Some code examples do not have variable and type definitions.

## Motivation

I don't know what is going on in some code examples due to undefined stuff.

## Drawbacks

Defining each thing for each code example can be oververbose.

## Unresolved questions

???

---

I would love working on it myself.

**Comment by torkleyy** [comment]
Thanks for creating an issue @yuvallanger!

If you want to work on that, I'm happy to take a PR! The book now is under `docs/tutorials/`. You can simply edit the files inside the `src` folder.

To build it locally, use: `mdbook build docs/tutorials`

Additionally, we could test the book code samples by `mdbook`. This is still a rather experimental feature, and as such, you usually need to run `cargo clean` and do a fresh `cargo build` to make it work.

To test the book with `mdbook`, we could use: `mdbook test docs/tutorials -L target/debug/deps`. Getting all the samples to work is a lot of work, so this is probably something we cannot do right now, but at some point in the future.

Feel free to ping me for any more questions.

**Comment by yuvallanger** [comment]
Trying to build the tutorial, I get this error:

```
$ mdbook build docs/tutorials
2019-06-15 20:02:04 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md
2019-06-15 20:02:04 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```

**Comment by torkleyy** [comment]
That's strange :sweat_smile: Are you sure your branch is up to date?

**Comment by yuvallanger** [comment]
Ooooh woops! I've checked out v0.14.3 before. Thank you!

```
$ mdbook build docs/tutorials
2019-06-15 20:08:08 [INFO] (mdbook::book): Book building has started
2019-06-15 20:08:08 [INFO] (mdbook::book): Running the html backend
$ find * -name SUMMARY.md
docs/tutorials/src/SUMMARY.md
docs/reference/src/SUMMARY.md
```

**Comment by yuvallanger** [comment]
What's your opinion with regard to enveloping examples of code with a function definition?

Using an example from `02_hello_world.md`:

```
let mut world = World::new();
world.register::<Position>();
world.register::<Velocity>();
```

to:

```
fn register_components_in_the_world() {
    let mut world = World::new();
    world.register::<Position>();
    world.register::<Velocity>();
}
```

Also, can I already open a pull request titled `[WIP] Add context to code examples in documentation.` with nothing yet done and work on it there? I could just start committing and ask for feedback directly on the code.

**Comment by torkleyy** [comment]
> `fn register_components_in_the_world() {`

Using a separate function makes sense, but I'd rather make it

`fn create_world() -> World`

And, yes, feel free to open a Pull Request and I'll give you feedback there.
