### ISSUE TITLE
[Question] Possible to join over dynamic resources

### ISSUE THREAD

**Issue by JoeHowarth** [slide-rs/specs#604]
I use specs as the data store and compute scheduler for a server side simulation and it works great. There's also a front-end that acts as a view of that simluation with communication over websockets. Following the dynamic system data example its definitely possible to get the storages dynamically and cast them to a particular trait, but I would ideally like to join over dynamic storages specified by the query. Does anyone know if this is possible?

**Comment by torkleyy** [comment]
This is possible, but it's not too pretty.

You can retrieve resources dynamically, as you mentioned, using dynamic system data. When you want to use any functionality of such storages, you'll have to cast them to a trait somehow.

There is a utility for this in shred, called [`MetaTable`](https://docs.rs/shred/0.8.1/shred/struct.MetaTable.html). However, the `Join` trait is not object-safe, which means you'll have to create your own dynamic wrapper for `Join`, which then yields its components as some sort of trait object.

So yes, it is technically possible, but it's definitely not very nice.

**Comment by JoeHowarth** [comment]
Thanks for the info! What do you mean by a dynamic wrapper exactly? I understand that `Join` isn't object safe because it references the Self type, but how does a wrapper circumvent this?
