### ISSUE TITLE
Send + Sync forced even with parallel disabled

### ISSUE THREAD

**Issue by SnowyCoder** [slide-rs/specs#614]
## Description
Is it necessary for a Component to implement both Send and Sync when the feature "parallel" is disabled?

## Motivation
When there is no multi-threading the developers do not need to send an object between threads, the implementation of Sync and Send shouldn't be required.

## Drawbacks

* Is it a breaking change? Proprably not.
* Can it impact performance, learnability, etc? It could make specs easier to develop in single-threaded environment.

## Unresolved questions

I'm new to rust so maybe this isn't possible, but an explaination on why it isn't should be provided somewhere (as well as the documentation of the "parallel" feature).

**Comment by torkleyy** [comment]
> Is it necessary for a Component to implement both Send and Sync when the feature "parallel" is disabled?

No, unfortunately we cannot do that, since features need to be additive. I.e., enabling `parallel` would break the code.

**Comment by SnowyCoder** [comment]
What if we negate it?
You could create a "single_thread" feature that disables the parallel code so that when you enable it the code shouldn't break (Sync and Send would still be implemented but they would not be used).
