### ISSUE TITLE
Correct way to pass storages to functions?

### ISSUE THREAD

**Issue by caelunshun** [slide-rs/specs#618]
What's the correct way to pass a component storage to a function? Passing a reference to a `ReadStorage` works fine, but there's no way to get a `ReadStorage` from a `WriteStorage`. Because of this, systems which have a `WriteStorage` instead of a `ReadStorage` won't be able to call the function.

**Comment by WaDelma** [comment]
Because
```rust
pub type ReadStorage<'a, T> = Storage<'a, T, Fetch<'a, MaskedStorage<T>>>;
```
and
```rust
pub type WriteStorage<'a, T> = Storage<'a, T, FetchMut<'a, MaskedStorage<T>>>;
```
you can do:
```rust
pub fn fun<'a, D>(&self, positions: &Storage<'a, Component, D>)
    where
        D: Deref<Target = MaskedStorage<Component>>,
```

**Comment by caelunshun** [comment]
Thanks!
