### ISSUE TITLE
Glium compatibility

### ISSUE THREAD

**Issue by ahmedaliadeel** [slide-rs/specs#67]
I will try that also but just courius to know in advance.

Will it work in either single thread or multi thread with Glium or Gfx?

**Comment by kvark** [comment]
It absolutely does work with Gfx. I got [yasteroids](https://github.com/kvark/yasteroids) as an example. Amethyst is also aiming to use Gfx+Specs in a multi-threading manner. Basically, you can populate command buffers in systems in parallel, and then send them over some channels to the context-owning thread for execution.

Glium interaction may be problem, although I haven't tried. We can leave the issue open to investigate that.

**Comment by ahmedaliadeel** [comment]
Thanks

**Comment by Kerosene2000** [comment]
@kvark Can you reopen this issue, please ? 😄

**Comment by ahmedaliadeel** [comment]
done

**Comment by thiolliere** [comment]
I don't know if it will really answer your question but I use specs with glium in my game [ruga](https://github.com/thiolliere/ruga) and here is how I made it:

* update, render and events are [decoupled](https://github.com/thiolliere/ruga/blob/master/src/main.rs#L183-L203) like in piston event loop
* the update method will call [planner dispatch and wait](https://github.com/thiolliere/ruga/blob/master/src/app.rs#L540-L541)
* the event handling and render methods [read and write world directly without parallelism](https://github.com/thiolliere/ruga/blob/master/src/app.rs#L610-L616)

**Comment by kvark** [comment]
I guess it can be closed now, thanks for @thiolliere answer?
