### ISSUE TITLE
Constructing entities manually

### ISSUE THREAD

**Issue by Aceeri** [slide-rs/specs#77]
Would be nice to be able to store a u32 and i32 instead of storing an `Entity`, mainly for Atomic types.

Are there any problems related to making the declaration `pub struct Generation(pub i32)`? Or maybe having a constructor for it?

**Comment by kvark** [comment]
That sounds quite unsafe. We could add an unsafe constructor for `Generation` if you have a use case.

**Comment by Aceeri** [comment]
No longer a problem for me at least. I was just trying to store an `Entity` atomically.
