### ISSUE TITLE
Unable to use components that require lifetime parameters

### ISSUE THREAD

**Issue by photex** [slide-rs/specs#83]
Howdy!

I was attempting to play around with radiant and specs but I've run into some trouble. Component requires Any... which requires the static lifetime. So it isn't possible (or it just isn't clear *how*) to create components that hold runtime resources.

Any advice here?

**Comment by photex** [comment]
Hrm... I think just realized this is the general case where we'd want a handle map. Is there a generic container out there for this yet? In specs or gfx perhaps?

**Comment by kvark** [comment]
@photex Hello!
I don't think anyone got a need for the lifetimed components. The problem here is that the component storages are accessed from worker threads that run in a thread pool. So in order to put any lifetime constraint these would have to be converted to the scoped threads.

As for the handle map, could you explain in more detail on what it is and where you'd need it?

I'd be very interested to see radiant+specs working together. I'm sure a lot of people are going to be interested in this!

**Comment by photex** [comment]
o/ @kvark 

Most stuff in radiant has an explicit lifetime. For example the [Sprite](https://sinesc.github.io/doc/radiant_rs/struct.Sprite.html)

Sprites can't be created without a RenderContext (also containing a lifetime), and that comes from the Renderer (also has a lifetime). So we can't really load any sprites or fonts without involving these things.

You can wrap a Layer with an Arc and stick that into a System which is handy when making a system for multithreaded updates and issuing draw commands. But when trying to create a Sprite component this issue came up.

So, you start your app or level, load your assets, and initialize entities and here is where I imagined the need for a handle map because I don't know how we can associate sprite resources with a component any other way. :)
Handle map may be the wrong name, but isn't that how gfx is managing it's resources? [another example](http://www.gamedev.net/page/resources/_/technical/general-programming/game-engine-containers-handle-map-r4495)

**Comment by photex** [comment]
I think we've found a solution using only what's at hand.

Our render system has a Sender to our main thread to submit draw commands (which are just enum values). The Sprite component just has a handle to a sprite which it includes and a layer id.

Not the final design but it's functioning within all the constraints.  We avoid referring to any radiant stuff directly within our ECS related code.

**Comment by sinesc** [comment]
I have since removed lifetime requirements from Sprite and a bunch of other things.
