### ISSUE TITLE
no thread version to compile to asmjs/wasm

### ISSUE THREAD

**Issue by thiolliere** [slide-rs/specs#84]
my game is using specs and I also want to be able to compile to asmjs.
But the web doesn't support thread for now.

What do you think about using a fake thread-pool when targeting those platform ?

**Comment by kvark** [comment]
I think there is a great demand in extending `specs` to support single-thread operation, hopefully with a simplified API. That would directly solve the Emscripten problem as well.

**Comment by torkleyy** [comment]
@thiolliere Is there a `cfg` flag to check if one of these platforms is the compilation target?

**Comment by thiolliere** [comment]
@torkleyy I use the flag `target_os = "emscripten"`

**Comment by torkleyy** [comment]
As far as I can see there is no compile-time failure when trying to use a thread, but rather a panic at runtime, am I right?

**Comment by thiolliere** [comment]
@torkleyy yes, as far as I remember

also threads may be available in emscipten once.
It needs sharedArrayBuffer which seem to be quite there. (shipped in safari, in development eveywhere else)

https://www.chromestatus.com/feature/4570991992766464
https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#Browser_compatibility

**Comment by torkleyy** [comment]
So should I even implement a non-threaded version for emsrcipten targets? Or just wait for the `SharedArrayBuffer`?

**Comment by minecrawler** [comment]
What about situations in which one wants to enforce single-threaded-ness? I could think of applications in embedded scenarios, when you have different hardware you must compile for, but want to get the most out of the stronger devices...

Hence, why not create a non-threaded feature flag, which can be used for emscripten targets for now?

**Comment by torkleyy** [comment]
Yes, I agree a single threaded version might be useful in some situations, also in a situation where you have very few systems and parallel execution would have too much overhead. I'm nearly finished with it, but I',m not sure if it should be a flag (assuming you are taling about a runtime flag). I'd propose the following to have two methods, `dispatch` and `dispatch_seq`, where `dispatch` redirects to `dispatch_seq` if a `parallel` feature is not set.

**Comment by vitvakatu** [comment]
@torkleyy I like your proposal

**Comment by minecrawler** [comment]
@torkleyy I meant a compile-time feature flag. It's the same as what you proposed with the absence of the `parallel` flag, just the other way around. So, I think, we agree :)
