### ISSUE TITLE
NullStorage could use PhantomData

### ISSUE THREAD

**Issue by HybridEidolon** [slide-rs/specs#85]
Is there any reason this code:

https://github.com/slide-rs/specs/blob/eabe112b4f06965dfcb9cf9129ac4b47375ca05c/src/storage.rs#L299

couldn't just use `std::marker::PhantomData<T>` instead of storing a default value and never actually using it? NullStorage would become a ZST if it did.

**Comment by kvark** [comment]
The only reason is that it has to return something for `get`:
```rust
unsafe fn get(&self, _: Index) -> &T { &self.0 }
```

**Comment by HybridEidolon** [comment]
Alright, and since it's a reference I guess that makes sense. I'll close this since I was thinking of sending in a PR for it.
