### ISSUE TITLE
Entity creation/deletion APIs

### ISSUE THREAD

**Issue by kvark** [slide-rs/specs#87]
This concern came up in #86.

We currently have:
 - `create_now` - needs `&mut self` and thus only applicable to early initialization
 - `create_later` - doesn't allow components building conveniently, so the usage is rather limited
 - `create_later_build` - much usable, but the name is long and confusing

I suggest we revise these APIs for specs-0.8. Basic proposal:
 - leave `create_now` as is, given that it's sufficiently expressive
 - rename `create_later_build` -> `create`, assuming it's what users actually want to use
 - rename `create_later` to `create_pure`, reflecting the fact only the `Entity` is created with no building.

Can we do better? cc @msiglreith @csherratt

**Comment by msiglreith** [comment]
I'm in favor of the renaming, definitely better than the current ones.
The new names should also be updated for `RunArg` (https://github.com/slide-rs/specs/blob/master/src/planner.rs#L43-L45)

**Comment by sinesc** [comment]
Would it be possible to get a more convenient API to create entities+components from within a system?
Unless I'm overlooking something, we're currently required to fetch() the component storages, create() an entity and then insert() the components into the storages.
There's a nice comment in https://github.com/slide-rs/specs/issues/48#issuecomment-262008082 on that issue as well

**Comment by kvark** [comment]
@sinesc there is another option, a simpler one:
https://github.com/kvark/yasteroids/blob/master/src/sys/bullet.rs#L82

**Comment by sinesc** [comment]
But can you do that after the system has iterated over the entities given that fetch() may only be used once?
Unless you're constantly shooting, you'll probably want to trigger spawn based on whatever happened during the iteration. I could not find a way to get a mutable world (for the entity builder) at that point in the system.

**Comment by kvark** [comment]
Right.
> you'll probably want to trigger spawn based on whatever happened during the iteration

Care to give an example?

**Comment by sinesc** [comment]
Something like spawning an entity with some property based on the one that spawned it, e.g. same directional vector, position, ...

**Comment by vitvakatu** [comment]
I'll do it

**Comment by kvark** [comment]
Fixed in #113
