### ISSUE TITLE
Deleting entity twice caused assertion error

### ISSUE THREAD

**Issue by TheSilvus** [slide-rs/specs#94]
Example Code:

```
let mut world = World::new();

let entity = world.create_now().build();

world.delete_now(entity);
world.delete_later(entity);

world.maintain();
```

Triggered assertion: https://github.com/slide-rs/specs/blob/master/src/lib.rs#L50

**Comment by kvark** [comment]
What would you expect `specs` to do in this case?

**Comment by TheSilvus** [comment]
I would expect it to either do nothing (ignore that the entity was deleted twice) or panic with a (useful) error message when deleting it (not sure whether this can be implemented well) - an assertion error usually means something went wrong inside the library.

**Comment by torkleyy** [comment]
@Aceeri my local code didn't seem to make any performance improvements, so I won't create a PR fixing this anytime soon.

If anybody is looking for an issue to solve, this one should be quite easy. If you need any help, just ask for it on Gitter.
