### ISSUE TITLE
Make registering components idempotent

### ISSUE THREAD

**Issue by jeffparsons** [slide-rs/specs#96]
I'd like to be able to have systems in my library automatically register any components they use upon initialisation, so that clients don't need to do that separately. The consequence of this is that multiple systems would attempt to register the same component type.

[`World::register`](https://slide-rs.github.io/specs/specs/struct.World.html#method.register) can't be used in that way directly, by the look of it because it doesn't keep track of what components are registered before blindly "re-initialising" the storage for the component type.

I thought of checking this myself using something like [TypeMap](https://github.com/reem/rust-typemap), then it occurred to me that you're effectively tracking the information necessary for this internally in Specs anyway, so it wouldn't be much of a stretch to make `register` idempotent`.

Any objection to this, or reason I've missed that it shouldn't be idempotent? I'm happy to implement it and PR if no objections.

**Comment by kvark** [comment]
@jeffparsons It sounds sensible to me. How about a separate `register_maybe` variant that returns a `bool`?

**Comment by jeffparsons** [comment]
@kvark How's this? https://github.com/slide-rs/specs/pull/98

**Comment by jeffparsons** [comment]
Replaced ~~#98~~ with https://github.com/slide-rs/specs/pull/99.

**Comment by jeffparsons** [comment]
I think we can call this one done. :)
